/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:AMMOTD[MAX_PLAYERS];

//Textdraws

//Player Textdraws
AMMOTD[playerid] = CreatePlayerTextDraw(playerid, 506.000000, 66.000000, "150");
PlayerTextDrawFont(playerid, AMMOTD[playerid], 1);
PlayerTextDrawLetterSize(playerid, AMMOTD[playerid], 0.312500, 1.350000);
PlayerTextDrawTextSize(playerid, AMMOTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, AMMOTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, AMMOTD[playerid], 0);
PlayerTextDrawAlignment(playerid, AMMOTD[playerid], 1);
PlayerTextDrawColor(playerid, AMMOTD[playerid], 16777215);
PlayerTextDrawBackgroundColor(playerid, AMMOTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, AMMOTD[playerid], 50);
PlayerTextDrawUseBox(playerid, AMMOTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, AMMOTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, AMMOTD[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
