/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:PublicTD[3];
new PlayerText:PURSUIT_BOX_TEXT[MAX_PLAYERS];

//Textdraws
PublicTD[0] = TextDrawCreate(16.000000, 228.000000, "ld_dual:white");
TextDrawFont(PublicTD[0], 4);
TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[0], 43.000000, 17.000000);
TextDrawSetOutline(PublicTD[0], 1);
TextDrawSetShadow(PublicTD[0], 0);
TextDrawAlignment(PublicTD[0], 1);
TextDrawColor(PublicTD[0], 65430);
TextDrawBackgroundColor(PublicTD[0], 255);
TextDrawBoxColor(PublicTD[0], 50);
TextDrawUseBox(PublicTD[0], 1);
TextDrawSetProportional(PublicTD[0], 1);
TextDrawSetSelectable(PublicTD[0], 0);

PublicTD[1] = TextDrawCreate(59.000000, 228.000000, "ld_dual:white");
TextDrawFont(PublicTD[1], 4);
TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[1], 43.000000, 17.000000);
TextDrawSetOutline(PublicTD[1], 1);
TextDrawSetShadow(PublicTD[1], 0);
TextDrawAlignment(PublicTD[1], 1);
TextDrawColor(PublicTD[1], -16777066);
TextDrawBackgroundColor(PublicTD[1], 255);
TextDrawBoxColor(PublicTD[1], 50);
TextDrawUseBox(PublicTD[1], 1);
TextDrawSetProportional(PublicTD[1], 1);
TextDrawSetSelectable(PublicTD[1], 0);

PublicTD[2] = TextDrawCreate(16.000000, 245.000000, "ld_dual:white");
TextDrawFont(PublicTD[2], 4);
TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
TextDrawTextSize(PublicTD[2], 86.000000, 36.500000);
TextDrawSetOutline(PublicTD[2], 1);
TextDrawSetShadow(PublicTD[2], 0);
TextDrawAlignment(PublicTD[2], 1);
TextDrawColor(PublicTD[2], 150);
TextDrawBackgroundColor(PublicTD[2], 255);
TextDrawBoxColor(PublicTD[2], 50);
TextDrawUseBox(PublicTD[2], 1);
TextDrawSetProportional(PublicTD[2], 1);
TextDrawSetSelectable(PublicTD[2], 0);


//Player Textdraws
PURSUIT_BOX_TEXT[playerid] = CreatePlayerTextDraw(playerid, 21.000000, 249.000000, "Time_remaining:_00:23~n~Suspect_left:_2~n~Your_state:_Police");
PlayerTextDrawFont(playerid, PURSUIT_BOX_TEXT[playerid], 1);
PlayerTextDrawLetterSize(playerid, PURSUIT_BOX_TEXT[playerid], 0.179166, 0.949999);
PlayerTextDrawTextSize(playerid, PURSUIT_BOX_TEXT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PURSUIT_BOX_TEXT[playerid], 0);
PlayerTextDrawSetShadow(playerid, PURSUIT_BOX_TEXT[playerid], 0);
PlayerTextDrawAlignment(playerid, PURSUIT_BOX_TEXT[playerid], 1);
PlayerTextDrawColor(playerid, PURSUIT_BOX_TEXT[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, PURSUIT_BOX_TEXT[playerid], 255);
PlayerTextDrawBoxColor(playerid, PURSUIT_BOX_TEXT[playerid], 50);
PlayerTextDrawUseBox(playerid, PURSUIT_BOX_TEXT[playerid], 0);
PlayerTextDrawSetProportional(playerid, PURSUIT_BOX_TEXT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, PURSUIT_BOX_TEXT[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
