/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:HBETD[MAX_PLAYERS][4];
new PlayerText:THIRSTBAR[MAX_PLAYERS];
new PlayerText:HUNGERBAR[MAX_PLAYERS];
new PlayerText:HUNGERTEXT[MAX_PLAYERS];
new PlayerText:THIRSTTEXT[MAX_PLAYERS];

//Textdraws

//Player Textdraws
HBETD[playerid][0] = CreatePlayerTextDraw(playerid, 583.000000, 134.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HBETD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, HBETD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HBETD[playerid][0], 22.500000, 22.500000);
PlayerTextDrawSetOutline(playerid, HBETD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, HBETD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, HBETD[playerid][0], 1);
PlayerTextDrawColor(playerid, HBETD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, HBETD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, HBETD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, HBETD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, HBETD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, HBETD[playerid][0], 0);

HBETD[playerid][1] = CreatePlayerTextDraw(playerid, 585.000000, 136.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HBETD[playerid][1], 4);
PlayerTextDrawLetterSize(playerid, HBETD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HBETD[playerid][1], 18.500000, 19.000000);
PlayerTextDrawSetOutline(playerid, HBETD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, HBETD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, HBETD[playerid][1], 1);
PlayerTextDrawColor(playerid, HBETD[playerid][1], 1296911871);
PlayerTextDrawBackgroundColor(playerid, HBETD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, HBETD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, HBETD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, HBETD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, HBETD[playerid][1], 0);

	THIRSTBAR[playerid] = CreatePlayerTextDraw(playerid, 585.000000, 136.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, THIRSTBAR[playerid], 4);
	PlayerTextDrawLetterSize(playerid, THIRSTBAR[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, THIRSTBAR[playerid], 18.500000, 19.000000);
	PlayerTextDrawSetOutline(playerid, THIRSTBAR[playerid], 1);
	PlayerTextDrawSetShadow(playerid, THIRSTBAR[playerid], 0);
	PlayerTextDrawAlignment(playerid, THIRSTBAR[playerid], 1);
	PlayerTextDrawColor(playerid, THIRSTBAR[playerid], 1687547391);
	PlayerTextDrawBackgroundColor(playerid, THIRSTBAR[playerid], 255);
	PlayerTextDrawBoxColor(playerid, THIRSTBAR[playerid], 50);
	PlayerTextDrawUseBox(playerid, THIRSTBAR[playerid], 1);
	PlayerTextDrawSetProportional(playerid, THIRSTBAR[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, THIRSTBAR[playerid], 0);

HBETD[playerid][2] = CreatePlayerTextDraw(playerid, 556.000000, 134.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HBETD[playerid][2], 4);
PlayerTextDrawLetterSize(playerid, HBETD[playerid][2], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HBETD[playerid][2], 22.500000, 22.500000);
PlayerTextDrawSetOutline(playerid, HBETD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, HBETD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, HBETD[playerid][2], 1);
PlayerTextDrawColor(playerid, HBETD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, HBETD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, HBETD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, HBETD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, HBETD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, HBETD[playerid][2], 0);

HBETD[playerid][3] = CreatePlayerTextDraw(playerid, 558.000000, 136.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HBETD[playerid][3], 4);
PlayerTextDrawLetterSize(playerid, HBETD[playerid][3], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HBETD[playerid][3], 18.500000, 19.000000);
PlayerTextDrawSetOutline(playerid, HBETD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, HBETD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, HBETD[playerid][3], 1);
PlayerTextDrawColor(playerid, HBETD[playerid][3], 1296911871);
PlayerTextDrawBackgroundColor(playerid, HBETD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, HBETD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, HBETD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, HBETD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, HBETD[playerid][3], 0);

HUNGERBAR[playerid] = CreatePlayerTextDraw(playerid, 558.000000, 136.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HUNGERBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, HUNGERBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HUNGERBAR[playerid], 18.500000, 19.000000);
PlayerTextDrawSetOutline(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, HUNGERBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawColor(playerid, HUNGERBAR[playerid], 852308735);
PlayerTextDrawBackgroundColor(playerid, HUNGERBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, HUNGERBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HUNGERBAR[playerid], 0);

	HUNGERTEXT[playerid] = CreatePlayerTextDraw(playerid, 567.000000, 139.000000, "100");
	PlayerTextDrawFont(playerid, HUNGERTEXT[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HUNGERTEXT[playerid], 0.212500, 1.200000);
	PlayerTextDrawTextSize(playerid, HUNGERTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUNGERTEXT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, HUNGERTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, HUNGERTEXT[playerid], 2);
	PlayerTextDrawColor(playerid, HUNGERTEXT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HUNGERTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HUNGERTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, HUNGERTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, HUNGERTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HUNGERTEXT[playerid], 0);

	THIRSTTEXT[playerid] = CreatePlayerTextDraw(playerid, 594.000000, 139.000000, "100");
	PlayerTextDrawFont(playerid, THIRSTTEXT[playerid], 1);
	PlayerTextDrawLetterSize(playerid, THIRSTTEXT[playerid], 0.212500, 1.200000);
	PlayerTextDrawTextSize(playerid, THIRSTTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, THIRSTTEXT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, THIRSTTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, THIRSTTEXT[playerid], 2);
	PlayerTextDrawColor(playerid, THIRSTTEXT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, THIRSTTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, THIRSTTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, THIRSTTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, THIRSTTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, THIRSTTEXT[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
