/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:NOTIFY_TD[MAX_PLAYERS][2];

//Textdraws

//Player Textdraws
NOTIFY_TD[playerid][0] = CreatePlayerTextDraw(playerid, 6.000000, 140.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, NOTIFY_TD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, NOTIFY_TD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, NOTIFY_TD[playerid][0], 210.500000, 15.000000);
PlayerTextDrawSetOutline(playerid, NOTIFY_TD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, NOTIFY_TD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, NOTIFY_TD[playerid][0], 1);
PlayerTextDrawColor(playerid, NOTIFY_TD[playerid][0], -676855633);
PlayerTextDrawBackgroundColor(playerid, NOTIFY_TD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, NOTIFY_TD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, NOTIFY_TD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, NOTIFY_TD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, NOTIFY_TD[playerid][0], 0);

NOTIFY_TD[playerid][1] = CreatePlayerTextDraw(playerid, 10.000000, 143.000000, "_");
PlayerTextDrawFont(playerid, NOTIFY_TD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, NOTIFY_TD[playerid][1], 0.133333, 0.800000);
PlayerTextDrawTextSize(playerid, NOTIFY_TD[playerid][1], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, NOTIFY_TD[playerid][1], 0);
PlayerTextDrawSetShadow(playerid, NOTIFY_TD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, NOTIFY_TD[playerid][1], 1);
PlayerTextDrawColor(playerid, NOTIFY_TD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, NOTIFY_TD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, NOTIFY_TD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, NOTIFY_TD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, NOTIFY_TD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, NOTIFY_TD[playerid][1], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
