/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:AMMO_GUI[MAX_PLAYERS];

//Textdraws

//Player Textdraws
AMMO_GUI[playerid] = CreatePlayerTextDraw(playerid, 519.000000, 66.000000, "1000");
PlayerTextDrawFont(playerid, AMMO_GUI[playerid], 1);
PlayerTextDrawLetterSize(playerid, AMMO_GUI[playerid], 0.237500, 1.149999);
PlayerTextDrawTextSize(playerid, AMMO_GUI[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, AMMO_GUI[playerid], 1);
PlayerTextDrawSetShadow(playerid, AMMO_GUI[playerid], 0);
PlayerTextDrawAlignment(playerid, AMMO_GUI[playerid], 2);
PlayerTextDrawColor(playerid, AMMO_GUI[playerid], -1061109505);
PlayerTextDrawBackgroundColor(playerid, AMMO_GUI[playerid], 255);
PlayerTextDrawBoxColor(playerid, AMMO_GUI[playerid], 50);
PlayerTextDrawUseBox(playerid, AMMO_GUI[playerid], 0);
PlayerTextDrawSetProportional(playerid, AMMO_GUI[playerid], 1);
PlayerTextDrawSetSelectable(playerid, AMMO_GUI[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
