/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:INTERACT_TD[MAX_PLAYERS][7];
new PlayerText:INTERACT_VEH[MAX_PLAYERS];
new PlayerText:INTERACT_ITEM[MAX_PLAYERS];
new PlayerText:INTERACT_INVOICE[MAX_PLAYERS];
new PlayerText:INTERACT_PHONE[MAX_PLAYERS];
new PlayerText:INTERACT_GENERAL[MAX_PLAYERS];
new PlayerText:INTERACT_JOB[MAX_PLAYERS];
new PlayerText:INTERACT_CLOSE[MAX_PLAYERS];

//Textdraws

//Player Textdraws


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
