/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][1];

//Textdraws

//Player Textdraws
GANGWARSCORE_TD[playerid] = CreatePlayerTextDraw(playerid, 9.000000, 256.000000, "~w~Grove_Street:_~g~0~n~~w~Triads:_~y~0~n~~w~DaNangBoys:_~b~0~n~~w~Rifa:_~y~0~n~~w~Ballas:_~p~0~n~~w~Russian:_~r~0");
PlayerTextDrawFont(playerid, GANGWARSCORE_TD[playerid], 2);
PlayerTextDrawLetterSize(playerid, GANGWARSCORE_TD[playerid], 0.200000, 1.100000);
PlayerTextDrawTextSize(playerid, GANGWARSCORE_TD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, GANGWARSCORE_TD[playerid], 1);
PlayerTextDrawSetShadow(playerid, GANGWARSCORE_TD[playerid], 0);
PlayerTextDrawAlignment(playerid, GANGWARSCORE_TD[playerid], 1);
PlayerTextDrawColor(playerid, GANGWARSCORE_TD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, GANGWARSCORE_TD[playerid], 255);
PlayerTextDrawBoxColor(playerid, GANGWARSCORE_TD[playerid], 50);
PlayerTextDrawUseBox(playerid, GANGWARSCORE_TD[playerid], 0);
PlayerTextDrawSetProportional(playerid, GANGWARSCORE_TD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, GANGWARSCORE_TD[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
