/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][1];

//Textdraws

//Player Textdraws
GPSTD[playerid] = CreatePlayerTextDraw(playerid, 151.000000, 395.000000, "Verona_Beach~n~Distance:_1000.0_Meter");
PlayerTextDrawFont(playerid, GPSTD[playerid], 1);
PlayerTextDrawLetterSize(playerid, GPSTD[playerid], 0.187500, 1.300000);
PlayerTextDrawTextSize(playerid, GPSTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, GPSTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, GPSTD[playerid], 0);
PlayerTextDrawAlignment(playerid, GPSTD[playerid], 1);
PlayerTextDrawColor(playerid, GPSTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, GPSTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, GPSTD[playerid], 50);
PlayerTextDrawUseBox(playerid, GPSTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, GPSTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, GPSTD[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
