/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][6];
new PlayerText:HUNGERBAR[MAX_PLAYERS];
new PlayerText:THIRSTBAR[MAX_PLAYERS];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 540.000000, 406.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 93.500000, 35.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 1296911792);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 545.000000, 396.000000, "Wellness");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.420832, 1.549999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 547.000000, 414.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 81.500000, 10.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1061109505);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

HUNGERBAR[playerid] = CreatePlayerTextDraw(playerid, 548.000000, 415.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HUNGERBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, HUNGERBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HUNGERBAR[playerid], 79.500000, 7.500000);
PlayerTextDrawSetOutline(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, HUNGERBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawColor(playerid, HUNGERBAR[playerid], 852308735);
PlayerTextDrawBackgroundColor(playerid, HUNGERBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, HUNGERBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HUNGERBAR[playerid], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 577.000000, 414.000000, "HUNGER");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.137500, 0.900000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 547.000000, 426.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 81.500000, 10.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1061109505);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

THIRSTBAR[playerid] = CreatePlayerTextDraw(playerid, 548.000000, 427.500000, "ld_dual:white");
PlayerTextDrawFont(playerid, THIRSTBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, THIRSTBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, THIRSTBAR[playerid], 79.500000, 7.500000);
PlayerTextDrawSetOutline(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, THIRSTBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawColor(playerid, THIRSTBAR[playerid], 1687547391);
PlayerTextDrawBackgroundColor(playerid, THIRSTBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, THIRSTBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, THIRSTBAR[playerid], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 579.000000, 426.000000, "THIRST");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.137500, 0.900000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
