/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:HUDTD[MAX_PLAYERS][21];
new PlayerText:THIRSTTD[MAX_PLAYERS];
new PlayerText:TIHRSTTEXT[MAX_PLAYERS];
new PlayerText:HUNGERTD[MAX_PLAYERS];
new PlayerText:HUNGERTEXT[MAX_PLAYERS];
new PlayerText:CASHTEXT[MAX_PLAYERS];
new PlayerText:FUELTD[MAX_PLAYERS];
new PlayerText:FUELTEXT[MAX_PLAYERS];
new PlayerText:VHPTD[MAX_PLAYERS];
new PlayerText:VHPTEXT[MAX_PLAYERS];
new PlayerText:SPEEDTEXT[MAX_PLAYERS];

//Textdraws

//Player Textdraws
	HUDTD[playerid][0] = CreatePlayerTextDraw(playerid, 584.000000, 425.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][0], 48.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][0], 175);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][0], 0);

	HUDTD[playerid][1] = CreatePlayerTextDraw(playerid, 585.000000, 426.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][1], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][1], 1296911791);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][1], 0);

	THIRSTTD[playerid] = CreatePlayerTextDraw(playerid, 585.000000, 426.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, THIRSTTD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, THIRSTTD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, THIRSTTD[playerid], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, THIRSTTD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, THIRSTTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, THIRSTTD[playerid], 1);
	PlayerTextDrawColor(playerid, THIRSTTD[playerid], 9145263);
	PlayerTextDrawBackgroundColor(playerid, THIRSTTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, THIRSTTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, THIRSTTD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, THIRSTTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, THIRSTTD[playerid], 0);

	HUDTD[playerid][2] = CreatePlayerTextDraw(playerid, 589.000000, 428.000000, "HUD:radar_diner");
	PlayerTextDrawFont(playerid, HUDTD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][2], 10.500000, 10.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][2], 0);

	TIHRSTTEXT[playerid] = CreatePlayerTextDraw(playerid, 612.000000, 429.000000, "100%");
	PlayerTextDrawFont(playerid, TIHRSTTEXT[playerid], 1);
	PlayerTextDrawLetterSize(playerid, TIHRSTTEXT[playerid], 0.195833, 0.900000);
	PlayerTextDrawTextSize(playerid, TIHRSTTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TIHRSTTEXT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, TIHRSTTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, TIHRSTTEXT[playerid], 2);
	PlayerTextDrawColor(playerid, TIHRSTTEXT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, TIHRSTTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, TIHRSTTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, TIHRSTTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, TIHRSTTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, TIHRSTTEXT[playerid], 0);

	HUDTD[playerid][3] = CreatePlayerTextDraw(playerid, 584.000000, 405.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][3], 48.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][3], 175);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][3], 0);

	HUDTD[playerid][4] = CreatePlayerTextDraw(playerid, 585.000000, 406.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][4], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][4], 1296911791);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][4], 0);

	HUNGERTD[playerid] = CreatePlayerTextDraw(playerid, 585.000000, 406.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUNGERTD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HUNGERTD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUNGERTD[playerid], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, HUNGERTD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HUNGERTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, HUNGERTD[playerid], 1);
	PlayerTextDrawColor(playerid, HUNGERTD[playerid], 852308655);
	PlayerTextDrawBackgroundColor(playerid, HUNGERTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HUNGERTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, HUNGERTD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HUNGERTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HUNGERTD[playerid], 0);

	HUDTD[playerid][5] = CreatePlayerTextDraw(playerid, 589.000000, 408.000000, "HUD:radar_pizza");
	PlayerTextDrawFont(playerid, HUDTD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][5], 10.500000, 10.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][5], 0);

	HUNGERTEXT[playerid] = CreatePlayerTextDraw(playerid, 612.000000, 409.000000, "100%");
	PlayerTextDrawFont(playerid, HUNGERTEXT[playerid], 1);
	PlayerTextDrawLetterSize(playerid, HUNGERTEXT[playerid], 0.195833, 0.900000);
	PlayerTextDrawTextSize(playerid, HUNGERTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUNGERTEXT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, HUNGERTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, HUNGERTEXT[playerid], 2);
	PlayerTextDrawColor(playerid, HUNGERTEXT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, HUNGERTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HUNGERTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, HUNGERTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, HUNGERTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HUNGERTEXT[playerid], 0);

	HUDTD[playerid][6] = CreatePlayerTextDraw(playerid, 584.000000, 385.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][6], 48.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][6], 175);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][6], 0);

	HUDTD[playerid][7] = CreatePlayerTextDraw(playerid, 585.000000, 386.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][7], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][7], 9109679);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][7], 0);

	CASHTEXT[playerid] = CreatePlayerTextDraw(playerid, 608.000000, 388.500000, "$100000.00,00");
	PlayerTextDrawFont(playerid, CASHTEXT[playerid], 2);
	PlayerTextDrawLetterSize(playerid, CASHTEXT[playerid], 0.116666, 0.900000);
	PlayerTextDrawTextSize(playerid, CASHTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, CASHTEXT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, CASHTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, CASHTEXT[playerid], 2);
	PlayerTextDrawColor(playerid, CASHTEXT[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, CASHTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, CASHTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, CASHTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, CASHTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, CASHTEXT[playerid], 0);

	HUDTD[playerid][8] = CreatePlayerTextDraw(playerid, 532.000000, 425.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][8], 48.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][8], 175);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][8], 0);

	HUDTD[playerid][9] = CreatePlayerTextDraw(playerid, 533.500000, 426.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][9], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][9], 1296911791);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][9], 0);

	FUELTD[playerid] = CreatePlayerTextDraw(playerid, 533.500000, 426.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, FUELTD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, FUELTD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, FUELTD[playerid], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, FUELTD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, FUELTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, FUELTD[playerid], 1);
	PlayerTextDrawColor(playerid, FUELTD[playerid], -764862801);
	PlayerTextDrawBackgroundColor(playerid, FUELTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FUELTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, FUELTD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, FUELTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FUELTD[playerid], 0);

	HUDTD[playerid][10] = CreatePlayerTextDraw(playerid, 537.000000, 435.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][10], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][10], 4.500000, 3.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][10], 0);

	HUDTD[playerid][11] = CreatePlayerTextDraw(playerid, 535.500000, 438.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][11], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][11], 8.000000, 1.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][11], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][11], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][11], 0);

	HUDTD[playerid][12] = CreatePlayerTextDraw(playerid, 536.500000, 429.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][12], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][12], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][12], 1.000000, 9.500000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][12], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][12], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][12], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][12], 0);

	HUDTD[playerid][13] = CreatePlayerTextDraw(playerid, 541.000000, 429.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][13], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][13], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][13], 0.500000, 8.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][13], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][13], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][13], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][13], 0);

	HUDTD[playerid][14] = CreatePlayerTextDraw(playerid, 541.000000, 430.000000, "]");
	PlayerTextDrawFont(playerid, HUDTD[playerid][14], 1);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][14], 0.200000, 0.700000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][14], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][14], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][14], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][14], 0);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][14], 0);

	FUELTEXT[playerid] = CreatePlayerTextDraw(playerid, 560.000000, 429.000000, "100%");
	PlayerTextDrawFont(playerid, FUELTEXT[playerid], 1);
	PlayerTextDrawLetterSize(playerid, FUELTEXT[playerid], 0.195833, 0.900000);
	PlayerTextDrawTextSize(playerid, FUELTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, FUELTEXT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, FUELTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, FUELTEXT[playerid], 2);
	PlayerTextDrawColor(playerid, FUELTEXT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, FUELTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FUELTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, FUELTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, FUELTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FUELTEXT[playerid], 0);

	HUDTD[playerid][15] = CreatePlayerTextDraw(playerid, 532.000000, 405.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][15], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][15], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][15], 48.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][15], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][15], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][15], 175);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][15], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][15], 0);

	HUDTD[playerid][16] = CreatePlayerTextDraw(playerid, 533.500000, 406.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][16], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][16], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][16], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][16], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][16], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][16], 1296911791);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][16], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][16], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][16], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][16], 0);

	VHPTD[playerid] = CreatePlayerTextDraw(playerid, 533.500000, 406.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, VHPTD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, VHPTD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, VHPTD[playerid], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, VHPTD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, VHPTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, VHPTD[playerid], 1);
	PlayerTextDrawColor(playerid, VHPTD[playerid], -16777041);
	PlayerTextDrawBackgroundColor(playerid, VHPTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, VHPTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, VHPTD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, VHPTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, VHPTD[playerid], 0);

	HUDTD[playerid][17] = CreatePlayerTextDraw(playerid, 537.000000, 408.000000, "HUD:radar_girlfriend");
	PlayerTextDrawFont(playerid, HUDTD[playerid][17], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][17], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][17], 10.500000, 10.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][17], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][17], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][17], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][17], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][17], 0);

	VHPTEXT[playerid] = CreatePlayerTextDraw(playerid, 562.000000, 409.000000, "2000.0");
	PlayerTextDrawFont(playerid, VHPTEXT[playerid], 1);
	PlayerTextDrawLetterSize(playerid, VHPTEXT[playerid], 0.195833, 0.900000);
	PlayerTextDrawTextSize(playerid, VHPTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, VHPTEXT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, VHPTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, VHPTEXT[playerid], 2);
	PlayerTextDrawColor(playerid, VHPTEXT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, VHPTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, VHPTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, VHPTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, VHPTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, VHPTEXT[playerid], 0);

	HUDTD[playerid][18] = CreatePlayerTextDraw(playerid, 532.000000, 385.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][18], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][18], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][18], 48.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][18], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][18], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][18], 175);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][18], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][18], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][18], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][18], 0);

	HUDTD[playerid][19] = CreatePlayerTextDraw(playerid, 533.500000, 386.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUDTD[playerid][19], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][19], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][19], 46.500000, 14.500000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][19], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][19], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][19], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][19], 1687547311);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][19], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][19], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][19], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][19], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][19], 0);

	HUDTD[playerid][20] = CreatePlayerTextDraw(playerid, 536.000000, 388.000000, "HUD:radar_sweet");
	PlayerTextDrawFont(playerid, HUDTD[playerid][20], 4);
	PlayerTextDrawLetterSize(playerid, HUDTD[playerid][20], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUDTD[playerid][20], 10.500000, 10.000000);
	PlayerTextDrawSetOutline(playerid, HUDTD[playerid][20], 1);
	PlayerTextDrawSetShadow(playerid, HUDTD[playerid][20], 0);
	PlayerTextDrawAlignment(playerid, HUDTD[playerid][20], 1);
	PlayerTextDrawColor(playerid, HUDTD[playerid][20], -1);
	PlayerTextDrawBackgroundColor(playerid, HUDTD[playerid][20], 255);
	PlayerTextDrawBoxColor(playerid, HUDTD[playerid][20], 50);
	PlayerTextDrawUseBox(playerid, HUDTD[playerid][20], 1);
	PlayerTextDrawSetProportional(playerid, HUDTD[playerid][20], 1);
	PlayerTextDrawSetSelectable(playerid, HUDTD[playerid][20], 0);

	SPEEDTEXT[playerid] = CreatePlayerTextDraw(playerid, 561.000000, 389.000000, "120KM/H");
	PlayerTextDrawFont(playerid, SPEEDTEXT[playerid], 1);
	PlayerTextDrawLetterSize(playerid, SPEEDTEXT[playerid], 0.175000, 0.900000);
	PlayerTextDrawTextSize(playerid, SPEEDTEXT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDTEXT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDTEXT[playerid], 0);
	PlayerTextDrawAlignment(playerid, SPEEDTEXT[playerid], 2);
	PlayerTextDrawColor(playerid, SPEEDTEXT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDTEXT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDTEXT[playerid], 50);
	PlayerTextDrawUseBox(playerid, SPEEDTEXT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDTEXT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDTEXT[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
