/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][11];
new PlayerText:HOMEBUTTON[MAX_PLAYERS];
new PlayerText:PHONECLOCK[MAX_PLAYERS];
new PlayerText:TWITTER_BG[MAX_PLAYERS];
new PlayerText:TWITTERMAIN_SIGNUP[MAX_PLAYERS];
new PlayerText:TWITTERMAIN_SIGNIN[MAX_PLAYERS];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 480.000000, 211.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 78.500000, 176.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 541.000000, 200.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 21.500000, 23.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 487.000000, 204.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 64.500000, 8.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 476.399993, 200.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 21.500000, 23.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 476.399993, 374.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 21.500000, 23.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 487.000000, 385.500000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 64.500000, 8.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 484.000000, 217.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 70.500000, 163.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 484.000000, 217.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 70.500000, 8.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], 195);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 515.000000, 382.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 8.500000, 9.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

HOMEBUTTON[playerid] = CreatePlayerTextDraw(playerid, 515.000000, 382.000000, "ld_beat:chit");
PlayerTextDrawFont(playerid, HOMEBUTTON[playerid], 4);
PlayerTextDrawLetterSize(playerid, HOMEBUTTON[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HOMEBUTTON[playerid], 8.500000, 9.500000);
PlayerTextDrawSetOutline(playerid, HOMEBUTTON[playerid], 1);
PlayerTextDrawSetShadow(playerid, HOMEBUTTON[playerid], 0);
PlayerTextDrawAlignment(playerid, HOMEBUTTON[playerid], 1);
PlayerTextDrawColor(playerid, HOMEBUTTON[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, HOMEBUTTON[playerid], 255);
PlayerTextDrawBoxColor(playerid, HOMEBUTTON[playerid], 50);
PlayerTextDrawUseBox(playerid, HOMEBUTTON[playerid], 1);
PlayerTextDrawSetProportional(playerid, HOMEBUTTON[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HOMEBUTTON[playerid], 1);

PHONECLOCK[playerid] = CreatePlayerTextDraw(playerid, 510.000000, 216.000000, "13:50");
PlayerTextDrawFont(playerid, PHONECLOCK[playerid], 2);
PlayerTextDrawLetterSize(playerid, PHONECLOCK[playerid], 0.150000, 0.949998);
PlayerTextDrawTextSize(playerid, PHONECLOCK[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PHONECLOCK[playerid], 0);
PlayerTextDrawSetShadow(playerid, PHONECLOCK[playerid], 0);
PlayerTextDrawAlignment(playerid, PHONECLOCK[playerid], 1);
PlayerTextDrawColor(playerid, PHONECLOCK[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, PHONECLOCK[playerid], 255);
PlayerTextDrawBoxColor(playerid, PHONECLOCK[playerid], 50);
PlayerTextDrawUseBox(playerid, PHONECLOCK[playerid], 0);
PlayerTextDrawSetProportional(playerid, PHONECLOCK[playerid], 1);
PlayerTextDrawSetSelectable(playerid, PHONECLOCK[playerid], 0);

TWITTER_BG[playerid] = CreatePlayerTextDraw(playerid, 484.000000, 225.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, TWITTER_BG[playerid], 4);
PlayerTextDrawLetterSize(playerid, TWITTER_BG[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, TWITTER_BG[playerid], 70.500000, 155.000000);
PlayerTextDrawSetOutline(playerid, TWITTER_BG[playerid], 1);
PlayerTextDrawSetShadow(playerid, TWITTER_BG[playerid], 0);
PlayerTextDrawAlignment(playerid, TWITTER_BG[playerid], 1);
PlayerTextDrawColor(playerid, TWITTER_BG[playerid], -61);
PlayerTextDrawBackgroundColor(playerid, TWITTER_BG[playerid], 255);
PlayerTextDrawBoxColor(playerid, TWITTER_BG[playerid], 50);
PlayerTextDrawUseBox(playerid, TWITTER_BG[playerid], 1);
PlayerTextDrawSetProportional(playerid, TWITTER_BG[playerid], 1);
PlayerTextDrawSetSelectable(playerid, TWITTER_BG[playerid], 0);

TWITTERMAIN_SIGNUP[playerid] = CreatePlayerTextDraw(playerid, 495.000000, 233.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, TWITTERMAIN_SIGNUP[playerid], 4);
PlayerTextDrawLetterSize(playerid, TWITTERMAIN_SIGNUP[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, TWITTERMAIN_SIGNUP[playerid], 49.500000, 11.000000);
PlayerTextDrawSetOutline(playerid, TWITTERMAIN_SIGNUP[playerid], 1);
PlayerTextDrawSetShadow(playerid, TWITTERMAIN_SIGNUP[playerid], 0);
PlayerTextDrawAlignment(playerid, TWITTERMAIN_SIGNUP[playerid], 1);
PlayerTextDrawColor(playerid, TWITTERMAIN_SIGNUP[playerid], 1687547351);
PlayerTextDrawBackgroundColor(playerid, TWITTERMAIN_SIGNUP[playerid], 255);
PlayerTextDrawBoxColor(playerid, TWITTERMAIN_SIGNUP[playerid], 50);
PlayerTextDrawUseBox(playerid, TWITTERMAIN_SIGNUP[playerid], 1);
PlayerTextDrawSetProportional(playerid, TWITTERMAIN_SIGNUP[playerid], 1);
PlayerTextDrawSetSelectable(playerid, TWITTERMAIN_SIGNUP[playerid], 1);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 510.500000, 233.500000, "Sign_Up");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.141665, 0.899998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

TWITTERMAIN_SIGNIN[playerid] = CreatePlayerTextDraw(playerid, 495.000000, 253.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, TWITTERMAIN_SIGNIN[playerid], 4);
PlayerTextDrawLetterSize(playerid, TWITTERMAIN_SIGNIN[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, TWITTERMAIN_SIGNIN[playerid], 49.500000, 11.000000);
PlayerTextDrawSetOutline(playerid, TWITTERMAIN_SIGNIN[playerid], 1);
PlayerTextDrawSetShadow(playerid, TWITTERMAIN_SIGNIN[playerid], 0);
PlayerTextDrawAlignment(playerid, TWITTERMAIN_SIGNIN[playerid], 1);
PlayerTextDrawColor(playerid, TWITTERMAIN_SIGNIN[playerid], 1687547351);
PlayerTextDrawBackgroundColor(playerid, TWITTERMAIN_SIGNIN[playerid], 255);
PlayerTextDrawBoxColor(playerid, TWITTERMAIN_SIGNIN[playerid], 50);
PlayerTextDrawUseBox(playerid, TWITTERMAIN_SIGNIN[playerid], 1);
PlayerTextDrawSetProportional(playerid, TWITTERMAIN_SIGNIN[playerid], 1);
PlayerTextDrawSetSelectable(playerid, TWITTERMAIN_SIGNIN[playerid], 1);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 510.500000, 253.500000, "Sign_In");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.141665, 0.899998);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
