/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:JAILTD[MAX_PLAYERS];

//Textdraws
//Player Textdraws
JAILTD[playerid] = CreatePlayerTextDraw(playerid, 150.000000, 393.000000, "~r~Jail_Time:~w~_00:20~n~~b~Jail_Reason:~w~_Unknown~n~~r~Jailed_by:~w~_vyn");
PlayerTextDrawFont(playerid, JAILTD[playerid], 1);
PlayerTextDrawLetterSize(playerid, JAILTD[playerid], 0.204166, 1.050000);
PlayerTextDrawTextSize(playerid, JAILTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, JAILTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, JAILTD[playerid], 0);
PlayerTextDrawAlignment(playerid, JAILTD[playerid], 1);
PlayerTextDrawColor(playerid, JAILTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, JAILTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, JAILTD[playerid], 50);
PlayerTextDrawUseBox(playerid, JAILTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, JAILTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, JAILTD[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
