/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:LOADBARTD[MAX_PLAYERS][2];
new PlayerText:TEXT[MAX_PLAYERS];

//Textdraws

//Player Textdraws
LOADBARTD[playerid][0] = CreatePlayerTextDraw(playerid, 264.000000, 346.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, LOADBARTD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, LOADBARTD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, LOADBARTD[playerid][0], 93.500000, 23.000000);
PlayerTextDrawSetOutline(playerid, LOADBARTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, LOADBARTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, LOADBARTD[playerid][0], 1);
PlayerTextDrawColor(playerid, LOADBARTD[playerid][0], 1296911728);
PlayerTextDrawBackgroundColor(playerid, LOADBARTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, LOADBARTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, LOADBARTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, LOADBARTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, LOADBARTD[playerid][0], 0);

LOADBARTD[playerid][1] = CreatePlayerTextDraw(playerid, 267.000000, 348.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, LOADBARTD[playerid][1], 4);
PlayerTextDrawLetterSize(playerid, LOADBARTD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, LOADBARTD[playerid][1], 88.000000, 18.500000);
PlayerTextDrawSetOutline(playerid, LOADBARTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, LOADBARTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, LOADBARTD[playerid][1], 1);
PlayerTextDrawColor(playerid, LOADBARTD[playerid][1], 16777136);
PlayerTextDrawBackgroundColor(playerid, LOADBARTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, LOADBARTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, LOADBARTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, LOADBARTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, LOADBARTD[playerid][1], 0);

TEXT[playerid] = CreatePlayerTextDraw(playerid, 310.000000, 349.000000, "sample_text");
PlayerTextDrawFont(playerid, TEXT[playerid], 1);
PlayerTextDrawLetterSize(playerid, TEXT[playerid], 0.204166, 1.500001);
PlayerTextDrawTextSize(playerid, TEXT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, TEXT[playerid], 0);
PlayerTextDrawSetShadow(playerid, TEXT[playerid], 0);
PlayerTextDrawAlignment(playerid, TEXT[playerid], 2);
PlayerTextDrawColor(playerid, TEXT[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, TEXT[playerid], 255);
PlayerTextDrawBoxColor(playerid, TEXT[playerid], 50);
PlayerTextDrawUseBox(playerid, TEXT[playerid], 0);
PlayerTextDrawSetProportional(playerid, TEXT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, TEXT[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
