/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][1];

//Textdraws

//Player Textdraws
LOBBYTD[playerid] = CreatePlayerTextDraw(playerid, 601.000000, 434.000000, "LOBBY:_5");
PlayerTextDrawFont(playerid, LOBBYTD[playerid], 2);
PlayerTextDrawLetterSize(playerid, LOBBYTD[playerid], 0.175000, 1.450000);
PlayerTextDrawTextSize(playerid, LOBBYTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, LOBBYTD[playerid], 0);
PlayerTextDrawSetShadow(playerid, LOBBYTD[playerid], 0);
PlayerTextDrawAlignment(playerid, LOBBYTD[playerid], 1);
PlayerTextDrawColor(playerid, LOBBYTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, LOBBYTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, LOBBYTD[playerid], 50);
PlayerTextDrawUseBox(playerid, LOBBYTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, LOBBYTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, LOBBYTD[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
