/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:MERPATIHUD[5];

//Textdraws
	MERPATIHUD[0] = TextDrawCreate(284.000000, 11.000000, "ld_dual:white");
	TextDrawFont(MERPATIHUD[0], 4);
	TextDrawLetterSize(MERPATIHUD[0], 0.600000, 2.000000);
	TextDrawTextSize(MERPATIHUD[0], 3.500000, 16.500000);
	TextDrawSetOutline(MERPATIHUD[0], 1);
	TextDrawSetShadow(MERPATIHUD[0], 0);
	TextDrawAlignment(MERPATIHUD[0], 1);
	TextDrawColor(MERPATIHUD[0], -16776961);
	TextDrawBackgroundColor(MERPATIHUD[0], 255);
	TextDrawBoxColor(MERPATIHUD[0], 50);
	TextDrawUseBox(MERPATIHUD[0], 1);
	TextDrawSetProportional(MERPATIHUD[0], 1);
	TextDrawSetSelectable(MERPATIHUD[0], 0);

	MERPATIHUD[1] = TextDrawCreate(288.000000, 17.000000, "ld_dual:white");
	TextDrawFont(MERPATIHUD[1], 4);
	TextDrawLetterSize(MERPATIHUD[1], 0.600000, 2.000000);
	TextDrawTextSize(MERPATIHUD[1], 3.500000, 10.500000);
	TextDrawSetOutline(MERPATIHUD[1], 1);
	TextDrawSetShadow(MERPATIHUD[1], 0);
	TextDrawAlignment(MERPATIHUD[1], 1);
	TextDrawColor(MERPATIHUD[1], -16776961);
	TextDrawBackgroundColor(MERPATIHUD[1], 255);
	TextDrawBoxColor(MERPATIHUD[1], 50);
	TextDrawUseBox(MERPATIHUD[1], 1);
	TextDrawSetProportional(MERPATIHUD[1], 1);
	TextDrawSetSelectable(MERPATIHUD[1], 0);

	MERPATIHUD[2] = TextDrawCreate(292.000000, 14.000000, "ld_dual:white");
	TextDrawFont(MERPATIHUD[2], 4);
	TextDrawLetterSize(MERPATIHUD[2], 0.600000, 2.000000);
	TextDrawTextSize(MERPATIHUD[2], 3.500000, 13.500000);
	TextDrawSetOutline(MERPATIHUD[2], 1);
	TextDrawSetShadow(MERPATIHUD[2], 0);
	TextDrawAlignment(MERPATIHUD[2], 1);
	TextDrawColor(MERPATIHUD[2], -16776961);
	TextDrawBackgroundColor(MERPATIHUD[2], 255);
	TextDrawBoxColor(MERPATIHUD[2], 50);
	TextDrawUseBox(MERPATIHUD[2], 1);
	TextDrawSetProportional(MERPATIHUD[2], 1);
	TextDrawSetSelectable(MERPATIHUD[2], 0);

	MERPATIHUD[3] = TextDrawCreate(298.000000, 19.000000, "MERPATI");
	TextDrawFont(MERPATIHUD[3], 1);
	TextDrawLetterSize(MERPATIHUD[3], 0.258333, 1.099999);
	TextDrawTextSize(MERPATIHUD[3], 400.000000, 17.000000);
	TextDrawSetOutline(MERPATIHUD[3], 1);
	TextDrawSetShadow(MERPATIHUD[3], 0);
	TextDrawAlignment(MERPATIHUD[3], 1);
	TextDrawColor(MERPATIHUD[3], -1);
	TextDrawBackgroundColor(MERPATIHUD[3], 255);
	TextDrawBoxColor(MERPATIHUD[3], 50);
	TextDrawUseBox(MERPATIHUD[3], 0);
	TextDrawSetProportional(MERPATIHUD[3], 1);
	TextDrawSetSelectable(MERPATIHUD[3], 0);

	MERPATIHUD[4] = TextDrawCreate(285.000000, 28.000000, "~y~ROLE ~w~PLAY");
	TextDrawFont(MERPATIHUD[4], 1);
	TextDrawLetterSize(MERPATIHUD[4], 0.200000, 0.899999);
	TextDrawTextSize(MERPATIHUD[4], 400.000000, 17.000000);
	TextDrawSetOutline(MERPATIHUD[4], 1);
	TextDrawSetShadow(MERPATIHUD[4], 0);
	TextDrawAlignment(MERPATIHUD[4], 1);
	TextDrawColor(MERPATIHUD[4], -1);
	TextDrawBackgroundColor(MERPATIHUD[4], 255);
	TextDrawBoxColor(MERPATIHUD[4], 50);
	TextDrawUseBox(MERPATIHUD[4], 0);
	TextDrawSetProportional(MERPATIHUD[4], 1);
	TextDrawSetSelectable(MERPATIHUD[4], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
