/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:HBEHUD[MAX_PLAYERS][19];
new PlayerText:EATBAR[MAX_PLAYERS];
new PlayerText:DRINKBAR[MAX_PLAYERS];
new PlayerText:MONEYAMOUNT[MAX_PLAYERS];
new PlayerText:FUELBAR[MAX_PLAYERS];
new PlayerText:VHPBAR[MAX_PLAYERS];

//Textdraws

//Player Textdraws

	HBEHUD[playerid][0] = CreatePlayerTextDraw(playerid, 600.000000, 410.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][0], 24.500000, 24.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][0], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][0], 174);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][0], 0);

	HBEHUD[playerid][1] = CreatePlayerTextDraw(playerid, 605.500000, 415.000000, "HUD:radar_burgershot");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][1], 13.500000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][1], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][1], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][1], 0);

	HBEHUD[playerid][2] = CreatePlayerTextDraw(playerid, 600.000000, 434.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][2], 24.500000, -3.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][2], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][2], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][2], 0);

	EATBAR[playerid] = CreatePlayerTextDraw(playerid, 600.000000, 431.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, EATBAR[playerid], 4);
	PlayerTextDrawLetterSize(playerid, EATBAR[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EATBAR[playerid], 24.500000, -21.500000);
	PlayerTextDrawSetOutline(playerid, EATBAR[playerid], 1);
	PlayerTextDrawSetShadow(playerid, EATBAR[playerid], 0);
	PlayerTextDrawAlignment(playerid, EATBAR[playerid], 1);
	PlayerTextDrawColor(playerid, EATBAR[playerid], -1962934195);
	PlayerTextDrawBackgroundColor(playerid, EATBAR[playerid], 255);
	PlayerTextDrawBoxColor(playerid, EATBAR[playerid], 50);
	PlayerTextDrawUseBox(playerid, EATBAR[playerid], 1);
	PlayerTextDrawSetProportional(playerid, EATBAR[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, EATBAR[playerid], 0);

	HBEHUD[playerid][3] = CreatePlayerTextDraw(playerid, 551.000000, 410.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][3], 24.500000, 24.500000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][3], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][3], 174);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][3], 0);

	HBEHUD[playerid][4] = CreatePlayerTextDraw(playerid, 557.500000, 415.000000, "HUD:radar_diner");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][4], 13.500000, 13.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][4], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][4], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][4], 0);

	DRINKBAR[playerid] = CreatePlayerTextDraw(playerid, 551.000000, 431.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, DRINKBAR[playerid], 4);
	PlayerTextDrawLetterSize(playerid, DRINKBAR[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, DRINKBAR[playerid], 24.500000, -21.500000);
	PlayerTextDrawSetOutline(playerid, DRINKBAR[playerid], 1);
	PlayerTextDrawSetShadow(playerid, DRINKBAR[playerid], 0);
	PlayerTextDrawAlignment(playerid, DRINKBAR[playerid], 1);
	PlayerTextDrawColor(playerid, DRINKBAR[playerid], -1962934195);
	PlayerTextDrawBackgroundColor(playerid, DRINKBAR[playerid], 255);
	PlayerTextDrawBoxColor(playerid, DRINKBAR[playerid], 50);
	PlayerTextDrawUseBox(playerid, DRINKBAR[playerid], 1);
	PlayerTextDrawSetProportional(playerid, DRINKBAR[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, DRINKBAR[playerid], 0);

	HBEHUD[playerid][5] = CreatePlayerTextDraw(playerid, 551.000000, 434.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][5], 24.500000, -3.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][5], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][5], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][5], 0);

	HBEHUD[playerid][6] = CreatePlayerTextDraw(playerid, 551.000000, 384.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][6], 73.500000, 17.500000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][6], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][6], 174);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][6], 0);

	HBEHUD[playerid][7] = CreatePlayerTextDraw(playerid, 551.000000, 384.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][7], 14.500000, 17.500000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][7], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][7], 174);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][7], 0);

	HBEHUD[playerid][8] = CreatePlayerTextDraw(playerid, 551.000000, 401.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][8], 73.500000, 3.500000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][8], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][8], -1962934017);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][8], 0);

	HBEHUD[playerid][9] = CreatePlayerTextDraw(playerid, 555.000000, 387.000000, "$");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][9], 2);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][9], 0.283333, 1.149999);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][9], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][9], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][9], 0);

	MONEYAMOUNT[playerid] = CreatePlayerTextDraw(playerid, 620.000000, 387.000000, "1.000.0000000000000");
	PlayerTextDrawFont(playerid, MONEYAMOUNT[playerid], 2);
	PlayerTextDrawLetterSize(playerid, MONEYAMOUNT[playerid], 0.112499, 1.100000);
	PlayerTextDrawTextSize(playerid, MONEYAMOUNT[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, MONEYAMOUNT[playerid], 0);
	PlayerTextDrawSetShadow(playerid, MONEYAMOUNT[playerid], 0);
	PlayerTextDrawAlignment(playerid, MONEYAMOUNT[playerid], 3);
	PlayerTextDrawColor(playerid, MONEYAMOUNT[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, MONEYAMOUNT[playerid], 255);
	PlayerTextDrawBoxColor(playerid, MONEYAMOUNT[playerid], 50);
	PlayerTextDrawUseBox(playerid, MONEYAMOUNT[playerid], 0);
	PlayerTextDrawSetProportional(playerid, MONEYAMOUNT[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, MONEYAMOUNT[playerid], 0);

	HBEHUD[playerid][10] = CreatePlayerTextDraw(playerid, 543.000000, 383.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][10], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][10], 1.500000, 50.500000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][10], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][10], 0);

	HBEHUD[playerid][11] = CreatePlayerTextDraw(playerid, 522.000000, 409.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][11], 5);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][11], 22.500000, 26.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][11], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][11], 0);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][11], 255);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][11], 0);
	PlayerTextDrawSetPreviewModel(playerid, HBEHUD[playerid][11], 1650);
	PlayerTextDrawSetPreviewRot(playerid, HBEHUD[playerid][11], -3.000000, 0.000000, 1.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, HBEHUD[playerid][11], 1, 1);

	HBEHUD[playerid][12] = CreatePlayerTextDraw(playerid, 523.000000, 386.000000, "100");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][12], 1);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][12], 0.283333, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][12], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][12], 3);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][12], 0);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][12], 0);

	HBEHUD[playerid][13] = CreatePlayerTextDraw(playerid, 538.000000, 393.000000, "KM/h");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][13], 1);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][13], 0.145833, 1.100000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][13], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][13], 3);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][13], 0);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][13], 0);

	HBEHUD[playerid][14] = CreatePlayerTextDraw(playerid, 521.000000, 410.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][14], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][14], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][14], 3.500000, 21.500000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][14], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][14], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][14], 174);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][14], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][14], 0);

	FUELBAR[playerid] = CreatePlayerTextDraw(playerid, 521.000000, 432.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, FUELBAR[playerid], 4);
	PlayerTextDrawLetterSize(playerid, FUELBAR[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, FUELBAR[playerid], 3.500000, -22.000000);
	PlayerTextDrawSetOutline(playerid, FUELBAR[playerid], 1);
	PlayerTextDrawSetShadow(playerid, FUELBAR[playerid], 0);
	PlayerTextDrawAlignment(playerid, FUELBAR[playerid], 1);
	PlayerTextDrawColor(playerid, FUELBAR[playerid], -764862802);
	PlayerTextDrawBackgroundColor(playerid, FUELBAR[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FUELBAR[playerid], 50);
	PlayerTextDrawUseBox(playerid, FUELBAR[playerid], 1);
	PlayerTextDrawSetProportional(playerid, FUELBAR[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FUELBAR[playerid], 0);

	HBEHUD[playerid][15] = CreatePlayerTextDraw(playerid, 521.000000, 434.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][15], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][15], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][15], 3.500000, -3.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][15], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][15], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][15], -764862721);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][15], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][15], 0);

	HBEHUD[playerid][16] = CreatePlayerTextDraw(playerid, 499.000000, 411.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][16], 5);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][16], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][16], 18.500000, 22.500000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][16], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][16], -1);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][16], 0);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][16], 255);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][16], 0);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][16], 0);
	PlayerTextDrawSetPreviewModel(playerid, HBEHUD[playerid][16], 1240);
	PlayerTextDrawSetPreviewRot(playerid, HBEHUD[playerid][16], -3.000000, 0.000000, 1.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, HBEHUD[playerid][16], 1, 1);

	HBEHUD[playerid][17] = CreatePlayerTextDraw(playerid, 494.000000, 410.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][17], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][17], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][17], 3.500000, 21.500000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][17], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][17], 174);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][17], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][17], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][17], 0);

	VHPBAR[playerid] = CreatePlayerTextDraw(playerid, 494.000000, 432.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, VHPBAR[playerid], 4);
	PlayerTextDrawLetterSize(playerid, VHPBAR[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, VHPBAR[playerid], 3.500000, -22.000000);
	PlayerTextDrawSetOutline(playerid, VHPBAR[playerid], 1);
	PlayerTextDrawSetShadow(playerid, VHPBAR[playerid], 0);
	PlayerTextDrawAlignment(playerid, VHPBAR[playerid], 1);
	PlayerTextDrawColor(playerid, VHPBAR[playerid], -16777042);
	PlayerTextDrawBackgroundColor(playerid, VHPBAR[playerid], 255);
	PlayerTextDrawBoxColor(playerid, VHPBAR[playerid], 50);
	PlayerTextDrawUseBox(playerid, VHPBAR[playerid], 1);
	PlayerTextDrawSetProportional(playerid, VHPBAR[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, VHPBAR[playerid], 0);

	HBEHUD[playerid][18] = CreatePlayerTextDraw(playerid, 494.000000, 434.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HBEHUD[playerid][18], 4);
	PlayerTextDrawLetterSize(playerid, HBEHUD[playerid][18], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HBEHUD[playerid][18], 3.500000, -3.000000);
	PlayerTextDrawSetOutline(playerid, HBEHUD[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, HBEHUD[playerid][18], 0);
	PlayerTextDrawAlignment(playerid, HBEHUD[playerid][18], 1);
	PlayerTextDrawColor(playerid, HBEHUD[playerid][18], -16776961);
	PlayerTextDrawBackgroundColor(playerid, HBEHUD[playerid][18], 255);
	PlayerTextDrawBoxColor(playerid, HBEHUD[playerid][18], 50);
	PlayerTextDrawUseBox(playerid, HBEHUD[playerid][18], 1);
	PlayerTextDrawSetProportional(playerid, HBEHUD[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, HBEHUD[playerid][18], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
