/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
static PlayerText:SEL_TD[MAX_PLAYERS][3];
static PlayerText:SEL_CONFIRM[MAX_PLAYERS];
static PlayerText:SEL_NEXT[MAX_PLAYERS];
static PlayerText:SEL_PREV[MAX_PLAYERS];
static PlayerText:SEL_MODEL[MAX_PLAYERS];
static PlayerText:SEL_DESCRIPTION[MAX_PLAYERS];
static PlayerText:SEL_TITLE[MAX_PLAYERS];

//Textdraws

//Player Textdraws
SEL_TD[playerid][0] = CreatePlayerTextDraw(playerid, 317.000000, 184.000000, "_");
PlayerTextDrawFont(playerid, SEL_TD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, SEL_TD[playerid][0], 0.645833, 15.049997);
PlayerTextDrawTextSize(playerid, SEL_TD[playerid][0], 298.500000, 235.000000);
PlayerTextDrawSetOutline(playerid, SEL_TD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, SEL_TD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, SEL_TD[playerid][0], 2);
PlayerTextDrawColor(playerid, SEL_TD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, SEL_TD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, SEL_TD[playerid][0], 135);
PlayerTextDrawUseBox(playerid, SEL_TD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, SEL_TD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, SEL_TD[playerid][0], 0);

SEL_TD[playerid][1] = CreatePlayerTextDraw(playerid, 317.000000, 309.000000, "_");
PlayerTextDrawFont(playerid, SEL_TD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, SEL_TD[playerid][1], 0.645833, 1.249999);
PlayerTextDrawTextSize(playerid, SEL_TD[playerid][1], 298.500000, 235.000000);
PlayerTextDrawSetOutline(playerid, SEL_TD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, SEL_TD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, SEL_TD[playerid][1], 2);
PlayerTextDrawColor(playerid, SEL_TD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, SEL_TD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, SEL_TD[playerid][1], 9145343);
PlayerTextDrawUseBox(playerid, SEL_TD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, SEL_TD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, SEL_TD[playerid][1], 0);

SEL_TD[playerid][2] = CreatePlayerTextDraw(playerid, 317.000000, 183.000000, "_");
PlayerTextDrawFont(playerid, SEL_TD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, SEL_TD[playerid][2], 0.645833, 1.249999);
PlayerTextDrawTextSize(playerid, SEL_TD[playerid][2], 298.500000, 235.000000);
PlayerTextDrawSetOutline(playerid, SEL_TD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, SEL_TD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, SEL_TD[playerid][2], 2);
PlayerTextDrawColor(playerid, SEL_TD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, SEL_TD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, SEL_TD[playerid][2], 9145343);
PlayerTextDrawUseBox(playerid, SEL_TD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, SEL_TD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, SEL_TD[playerid][2], 0);

SEL_CONFIRM[playerid] = CreatePlayerTextDraw(playerid, 222.000000, 307.000000, "CONFIRM");
PlayerTextDrawFont(playerid, SEL_CONFIRM[playerid], 1);
PlayerTextDrawLetterSize(playerid, SEL_CONFIRM[playerid], 0.200000, 1.400001);
PlayerTextDrawTextSize(playerid, SEL_CONFIRM[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, SEL_CONFIRM[playerid], 0);
PlayerTextDrawSetShadow(playerid, SEL_CONFIRM[playerid], 0);
PlayerTextDrawAlignment(playerid, SEL_CONFIRM[playerid], 2);
PlayerTextDrawColor(playerid, SEL_CONFIRM[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, SEL_CONFIRM[playerid], 255);
PlayerTextDrawBoxColor(playerid, SEL_CONFIRM[playerid], 50);
PlayerTextDrawUseBox(playerid, SEL_CONFIRM[playerid], 0);
PlayerTextDrawSetProportional(playerid, SEL_CONFIRM[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SEL_CONFIRM[playerid], 1);

SEL_NEXT[playerid] = CreatePlayerTextDraw(playerid, 416.000000, 307.000000, "NEXT");
PlayerTextDrawFont(playerid, SEL_NEXT[playerid], 1);
PlayerTextDrawLetterSize(playerid, SEL_NEXT[playerid], 0.200000, 1.400001);
PlayerTextDrawTextSize(playerid, SEL_NEXT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, SEL_NEXT[playerid], 0);
PlayerTextDrawSetShadow(playerid, SEL_NEXT[playerid], 0);
PlayerTextDrawAlignment(playerid, SEL_NEXT[playerid], 2);
PlayerTextDrawColor(playerid, SEL_NEXT[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, SEL_NEXT[playerid], 255);
PlayerTextDrawBoxColor(playerid, SEL_NEXT[playerid], 50);
PlayerTextDrawUseBox(playerid, SEL_NEXT[playerid], 0);
PlayerTextDrawSetProportional(playerid, SEL_NEXT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SEL_NEXT[playerid], 1);

SEL_PREV[playerid] = CreatePlayerTextDraw(playerid, 370.000000, 307.000000, "PREV");
PlayerTextDrawFont(playerid, SEL_PREV[playerid], 1);
PlayerTextDrawLetterSize(playerid, SEL_PREV[playerid], 0.200000, 1.400001);
PlayerTextDrawTextSize(playerid, SEL_PREV[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, SEL_PREV[playerid], 0);
PlayerTextDrawSetShadow(playerid, SEL_PREV[playerid], 0);
PlayerTextDrawAlignment(playerid, SEL_PREV[playerid], 2);
PlayerTextDrawColor(playerid, SEL_PREV[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, SEL_PREV[playerid], 255);
PlayerTextDrawBoxColor(playerid, SEL_PREV[playerid], 50);
PlayerTextDrawUseBox(playerid, SEL_PREV[playerid], 0);
PlayerTextDrawSetProportional(playerid, SEL_PREV[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SEL_PREV[playerid], 1);

SEL_MODEL[playerid] = CreatePlayerTextDraw(playerid, 260.000000, 169.000000, "Preview_Model");
PlayerTextDrawFont(playerid, SEL_MODEL[playerid], 5);
PlayerTextDrawLetterSize(playerid, SEL_MODEL[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, SEL_MODEL[playerid], 118.500000, 152.500000);
PlayerTextDrawSetOutline(playerid, SEL_MODEL[playerid], 0);
PlayerTextDrawSetShadow(playerid, SEL_MODEL[playerid], 0);
PlayerTextDrawAlignment(playerid, SEL_MODEL[playerid], 1);
PlayerTextDrawColor(playerid, SEL_MODEL[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, SEL_MODEL[playerid], 0);
PlayerTextDrawBoxColor(playerid, SEL_MODEL[playerid], 255);
PlayerTextDrawUseBox(playerid, SEL_MODEL[playerid], 0);
PlayerTextDrawSetProportional(playerid, SEL_MODEL[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SEL_MODEL[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, SEL_MODEL[playerid], 562);
PlayerTextDrawSetPreviewRot(playerid, SEL_MODEL[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, SEL_MODEL[playerid], 1, 1);

SEL_DESCRIPTION[playerid] = CreatePlayerTextDraw(playerid, 206.000000, 203.000000, "ELEGY");
PlayerTextDrawFont(playerid, SEL_DESCRIPTION[playerid], 1);
PlayerTextDrawLetterSize(playerid, SEL_DESCRIPTION[playerid], 0.200000, 1.400001);
PlayerTextDrawTextSize(playerid, SEL_DESCRIPTION[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, SEL_DESCRIPTION[playerid], 0);
PlayerTextDrawSetShadow(playerid, SEL_DESCRIPTION[playerid], 0);
PlayerTextDrawAlignment(playerid, SEL_DESCRIPTION[playerid], 1);
PlayerTextDrawColor(playerid, SEL_DESCRIPTION[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, SEL_DESCRIPTION[playerid], 255);
PlayerTextDrawBoxColor(playerid, SEL_DESCRIPTION[playerid], 50);
PlayerTextDrawUseBox(playerid, SEL_DESCRIPTION[playerid], 0);
PlayerTextDrawSetProportional(playerid, SEL_DESCRIPTION[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SEL_DESCRIPTION[playerid], 0);

SEL_TITLE[playerid] = CreatePlayerTextDraw(playerid, 315.000000, 181.000000, "VEHICLE_SELECTION");
PlayerTextDrawFont(playerid, SEL_TITLE[playerid], 2);
PlayerTextDrawLetterSize(playerid, SEL_TITLE[playerid], 0.200000, 1.400001);
PlayerTextDrawTextSize(playerid, SEL_TITLE[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, SEL_TITLE[playerid], 0);
PlayerTextDrawSetShadow(playerid, SEL_TITLE[playerid], 0);
PlayerTextDrawAlignment(playerid, SEL_TITLE[playerid], 2);
PlayerTextDrawColor(playerid, SEL_TITLE[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, SEL_TITLE[playerid], 255);
PlayerTextDrawBoxColor(playerid, SEL_TITLE[playerid], 50);
PlayerTextDrawUseBox(playerid, SEL_TITLE[playerid], 0);
PlayerTextDrawSetProportional(playerid, SEL_TITLE[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SEL_TITLE[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
