/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:MVPTD[MAX_PLAYERS][9];

//Textdraws

//Player Textdraws
MVPTD[playerid][0] = CreatePlayerTextDraw(playerid, 319.000000, 9.000000, "_");
PlayerTextDrawFont(playerid, MVPTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][0], 1.016666, 10.300003);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][0], 343.500000, 150.000000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][0], 2);
PlayerTextDrawColor(playerid, MVPTD[playerid][0], -1094795521);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][0], -1094795521);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][0], 0);

MVPTD[playerid][1] = CreatePlayerTextDraw(playerid, 319.000000, 9.000000, "_");
PlayerTextDrawFont(playerid, MVPTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][1], 1.016666, 1.300000);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][1], 343.500000, 150.000000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][1], 2);
PlayerTextDrawColor(playerid, MVPTD[playerid][1], -1094795521);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][1], -764862721);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][1], 0);

MVPTD[playerid][2] = CreatePlayerTextDraw(playerid, 264.000000, 8.000000, "MVP of The Match");
PlayerTextDrawFont(playerid, MVPTD[playerid][2], 2);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][2], 0.262500, 1.200000);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][2], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][2], 1);
PlayerTextDrawColor(playerid, MVPTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][2], 0);

MVPTD[playerid][3] = CreatePlayerTextDraw(playerid, 228.000000, 25.000000, "Preview_Model");
PlayerTextDrawFont(playerid, MVPTD[playerid][3], 5);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][3], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][3], 67.500000, 75.500000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][3], 1);
PlayerTextDrawColor(playerid, MVPTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][3], 0);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][3], 255);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][3], 0);
PlayerTextDrawSetPreviewModel(playerid, MVPTD[playerid][3], 0);
PlayerTextDrawSetPreviewRot(playerid, MVPTD[playerid][3], -7.000000, 0.000000, -3.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, MVPTD[playerid][3], 1, 1);

MVPTD[playerid][4] = CreatePlayerTextDraw(playerid, 321.000000, 24.000000, "DenvirTauno");
PlayerTextDrawFont(playerid, MVPTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][4], 0.262500, 1.200000);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][4], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][4], 2);
PlayerTextDrawColor(playerid, MVPTD[playerid][4], -65281);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][4], 0);

MVPTD[playerid][5] = CreatePlayerTextDraw(playerid, 278.000000, 40.000000, "Kills: 20");
PlayerTextDrawFont(playerid, MVPTD[playerid][5], 2);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][5], 0.229166, 1.150000);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][5], 1);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][5], 1);
PlayerTextDrawColor(playerid, MVPTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][5], 0);

MVPTD[playerid][6] = CreatePlayerTextDraw(playerid, 278.000000, 52.000000, "ASSIST: 20");
PlayerTextDrawFont(playerid, MVPTD[playerid][6], 2);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][6], 0.229166, 1.150000);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][6], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][6], 1);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][6], 1);
PlayerTextDrawColor(playerid, MVPTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][6], 0);

MVPTD[playerid][7] = CreatePlayerTextDraw(playerid, 278.000000, 65.000000, "STATE: Police");
PlayerTextDrawFont(playerid, MVPTD[playerid][7], 2);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][7], 0.229166, 1.150000);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][7], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][7], 1);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][7], 1);
PlayerTextDrawColor(playerid, MVPTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][7], 50);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][7], 0);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][7], 0);

MVPTD[playerid][8] = CreatePlayerTextDraw(playerid, 278.000000, 79.000000, "WinRate: 20.3%");
PlayerTextDrawFont(playerid, MVPTD[playerid][8], 2);
PlayerTextDrawLetterSize(playerid, MVPTD[playerid][8], 0.229166, 1.150000);
PlayerTextDrawTextSize(playerid, MVPTD[playerid][8], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, MVPTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, MVPTD[playerid][8], 1);
PlayerTextDrawAlignment(playerid, MVPTD[playerid][8], 1);
PlayerTextDrawColor(playerid, MVPTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, MVPTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, MVPTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, MVPTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, MVPTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, MVPTD[playerid][8], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
