/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][2];
new PlayerText:ARAHANGIN[MAX_PLAYERS];
new PlayerText:NAMAJALAN[MAX_PLAYERS];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 167.000000, 395.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 2.000000, 28.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1061109505);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

ARAHANGIN[playerid] = CreatePlayerTextDraw(playerid, 151.000000, 402.000000, "WSW");
PlayerTextDrawFont(playerid, ARAHANGIN[playerid], 1);
PlayerTextDrawLetterSize(playerid, ARAHANGIN[playerid], 0.304166, 1.899999);
PlayerTextDrawTextSize(playerid, ARAHANGIN[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, ARAHANGIN[playerid], 1);
PlayerTextDrawSetShadow(playerid, ARAHANGIN[playerid], 0);
PlayerTextDrawAlignment(playerid, ARAHANGIN[playerid], 2);
PlayerTextDrawColor(playerid, ARAHANGIN[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, ARAHANGIN[playerid], 255);
PlayerTextDrawBoxColor(playerid, ARAHANGIN[playerid], 50);
PlayerTextDrawUseBox(playerid, ARAHANGIN[playerid], 0);
PlayerTextDrawSetProportional(playerid, ARAHANGIN[playerid], 1);
PlayerTextDrawSetSelectable(playerid, ARAHANGIN[playerid], 0);

NAMAJALAN[playerid] = CreatePlayerTextDraw(playerid, 174.000000, 410.000000, "Randolph Industrial Estate");
PlayerTextDrawFont(playerid, NAMAJALAN[playerid], 1);
PlayerTextDrawLetterSize(playerid, NAMAJALAN[playerid], 0.204165, 1.200000);
PlayerTextDrawTextSize(playerid, NAMAJALAN[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, NAMAJALAN[playerid], 1);
PlayerTextDrawSetShadow(playerid, NAMAJALAN[playerid], 0);
PlayerTextDrawAlignment(playerid, NAMAJALAN[playerid], 1);
PlayerTextDrawColor(playerid, NAMAJALAN[playerid], -764862721);
PlayerTextDrawBackgroundColor(playerid, NAMAJALAN[playerid], 255);
PlayerTextDrawBoxColor(playerid, NAMAJALAN[playerid], 50);
PlayerTextDrawUseBox(playerid, NAMAJALAN[playerid], 0);
PlayerTextDrawSetProportional(playerid, NAMAJALAN[playerid], 1);
PlayerTextDrawSetSelectable(playerid, NAMAJALAN[playerid], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 174.000000, 398.000000, "San Andreas");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.170833, 1.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1094795521);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
