/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:HUD2_TD[13];
new PlayerText:HUNGERBAR_2[MAX_PLAYERS];
new PlayerText:THIRSTBAR_2[MAX_PLAYERS];
new PlayerText:SPEEDO_2[MAX_PLAYERS];

//Textdraws
HUD2_TD[0] = TextDrawCreate(606.000000, 408.000000, "_");
TextDrawFont(HUD2_TD[0], 0);
TextDrawLetterSize(HUD2_TD[0], 0.600000, 2.500000);
TextDrawTextSize(HUD2_TD[0], 298.500000, 20.000000);
TextDrawSetOutline(HUD2_TD[0], 1);
TextDrawSetShadow(HUD2_TD[0], 0);
TextDrawAlignment(HUD2_TD[0], 2);
TextDrawColor(HUD2_TD[0], -1);
TextDrawBackgroundColor(HUD2_TD[0], 255);
TextDrawBoxColor(HUD2_TD[0], 209);
TextDrawUseBox(HUD2_TD[0], 1);
TextDrawSetProportional(HUD2_TD[0], 1);
TextDrawSetSelectable(HUD2_TD[0], 0);

HUD2_TD[1] = TextDrawCreate(594.500000, 433.500000, "ld_dual:white");
TextDrawFont(HUD2_TD[1], 4);
TextDrawLetterSize(HUD2_TD[1], 0.600000, 2.000000);
TextDrawTextSize(HUD2_TD[1], 23.399999, 3.500000);
TextDrawSetOutline(HUD2_TD[1], 1);
TextDrawSetShadow(HUD2_TD[1], 0);
TextDrawAlignment(HUD2_TD[1], 1);
TextDrawColor(HUD2_TD[1], -1061109505);
TextDrawBackgroundColor(HUD2_TD[1], 255);
TextDrawBoxColor(HUD2_TD[1], 255);
TextDrawUseBox(HUD2_TD[1], 1);
TextDrawSetProportional(HUD2_TD[1], 1);
TextDrawSetSelectable(HUD2_TD[1], 0);

HUD2_TD[2] = TextDrawCreate(608.500000, 404.000000, "I");
TextDrawFont(HUD2_TD[2], 2);
TextDrawLetterSize(HUD2_TD[2], 0.216665, 3.199997);
TextDrawTextSize(HUD2_TD[2], 400.000000, 17.000000);
TextDrawSetOutline(HUD2_TD[2], 0);
TextDrawSetShadow(HUD2_TD[2], 0);
TextDrawAlignment(HUD2_TD[2], 1);
TextDrawColor(HUD2_TD[2], -1);
TextDrawBackgroundColor(HUD2_TD[2], 255);
TextDrawBoxColor(HUD2_TD[2], 50);
TextDrawUseBox(HUD2_TD[2], 0);
TextDrawSetProportional(HUD2_TD[2], 1);
TextDrawSetSelectable(HUD2_TD[2], 0);

HUD2_TD[3] = TextDrawCreate(607.000000, 386.000000, ".");
TextDrawFont(HUD2_TD[3], 1);
TextDrawLetterSize(HUD2_TD[3], 0.520833, 4.199999);
TextDrawTextSize(HUD2_TD[3], 400.000000, 17.000000);
TextDrawSetOutline(HUD2_TD[3], 0);
TextDrawSetShadow(HUD2_TD[3], 0);
TextDrawAlignment(HUD2_TD[3], 1);
TextDrawColor(HUD2_TD[3], -1);
TextDrawBackgroundColor(HUD2_TD[3], 255);
TextDrawBoxColor(HUD2_TD[3], 50);
TextDrawUseBox(HUD2_TD[3], 0);
TextDrawSetProportional(HUD2_TD[3], 1);
TextDrawSetSelectable(HUD2_TD[3], 0);

HUD2_TD[4] = TextDrawCreate(601.500000, 404.000000, "I");
TextDrawFont(HUD2_TD[4], 2);
TextDrawLetterSize(HUD2_TD[4], 0.216665, 3.199997);
TextDrawTextSize(HUD2_TD[4], 400.000000, 17.000000);
TextDrawSetOutline(HUD2_TD[4], 0);
TextDrawSetShadow(HUD2_TD[4], 0);
TextDrawAlignment(HUD2_TD[4], 1);
TextDrawColor(HUD2_TD[4], -1);
TextDrawBackgroundColor(HUD2_TD[4], 255);
TextDrawBoxColor(HUD2_TD[4], 50);
TextDrawUseBox(HUD2_TD[4], 0);
TextDrawSetProportional(HUD2_TD[4], 1);
TextDrawSetSelectable(HUD2_TD[4], 0);

HUD2_TD[5] = TextDrawCreate(572.500000, 411.000000, "U");
TextDrawFont(HUD2_TD[5], 1);
TextDrawLetterSize(HUD2_TD[5], 0.508333, 1.200000);
TextDrawTextSize(HUD2_TD[5], 400.000000, 17.000000);
TextDrawSetOutline(HUD2_TD[5], 0);
TextDrawSetShadow(HUD2_TD[5], 0);
TextDrawAlignment(HUD2_TD[5], 1);
TextDrawColor(HUD2_TD[5], -1);
TextDrawBackgroundColor(HUD2_TD[5], 255);
TextDrawBoxColor(HUD2_TD[5], 50);
TextDrawUseBox(HUD2_TD[5], 0);
TextDrawSetProportional(HUD2_TD[5], 1);
TextDrawSetSelectable(HUD2_TD[5], 0);

HUD2_TD[6] = TextDrawCreate(600.000000, 413.000000, ".");
TextDrawFont(HUD2_TD[6], 1);
TextDrawLetterSize(HUD2_TD[6], 0.520833, 0.699999);
TextDrawTextSize(HUD2_TD[6], 400.000000, 17.000000);
TextDrawSetOutline(HUD2_TD[6], 0);
TextDrawSetShadow(HUD2_TD[6], 0);
TextDrawAlignment(HUD2_TD[6], 1);
TextDrawColor(HUD2_TD[6], -1);
TextDrawBackgroundColor(HUD2_TD[6], 255);
TextDrawBoxColor(HUD2_TD[6], 50);
TextDrawUseBox(HUD2_TD[6], 0);
TextDrawSetProportional(HUD2_TD[6], 1);
TextDrawSetSelectable(HUD2_TD[6], 0);

HUD2_TD[7] = TextDrawCreate(603.500000, 410.000000, "I");
TextDrawFont(HUD2_TD[7], 1);
TextDrawLetterSize(HUD2_TD[7], 0.187500, 1.099998);
TextDrawTextSize(HUD2_TD[7], 396.500000, 14.000000);
TextDrawSetOutline(HUD2_TD[7], 0);
TextDrawSetShadow(HUD2_TD[7], 0);
TextDrawAlignment(HUD2_TD[7], 1);
TextDrawColor(HUD2_TD[7], -1);
TextDrawBackgroundColor(HUD2_TD[7], 255);
TextDrawBoxColor(HUD2_TD[7], 50);
TextDrawUseBox(HUD2_TD[7], 0);
TextDrawSetProportional(HUD2_TD[7], 1);
TextDrawSetSelectable(HUD2_TD[7], 0);

HUD2_TD[8] = TextDrawCreate(599.500000, 409.600006, "I");
TextDrawFont(HUD2_TD[8], 1);
TextDrawLetterSize(HUD2_TD[8], 0.170833, 1.099998);
TextDrawTextSize(HUD2_TD[8], 396.500000, 14.000000);
TextDrawSetOutline(HUD2_TD[8], 0);
TextDrawSetShadow(HUD2_TD[8], 0);
TextDrawAlignment(HUD2_TD[8], 1);
TextDrawColor(HUD2_TD[8], -1);
TextDrawBackgroundColor(HUD2_TD[8], 255);
TextDrawBoxColor(HUD2_TD[8], 50);
TextDrawUseBox(HUD2_TD[8], 0);
TextDrawSetProportional(HUD2_TD[8], 1);
TextDrawSetSelectable(HUD2_TD[8], 0);

HUD2_TD[9] = TextDrawCreate(578.000000, 408.000000, "_");
TextDrawFont(HUD2_TD[9], 0);
TextDrawLetterSize(HUD2_TD[9], 0.600000, 2.500000);
TextDrawTextSize(HUD2_TD[9], 298.500000, 20.000000);
TextDrawSetOutline(HUD2_TD[9], 1);
TextDrawSetShadow(HUD2_TD[9], 0);
TextDrawAlignment(HUD2_TD[9], 2);
TextDrawColor(HUD2_TD[9], -1);
TextDrawBackgroundColor(HUD2_TD[9], 255);
TextDrawBoxColor(HUD2_TD[9], 209);
TextDrawUseBox(HUD2_TD[9], 1);
TextDrawSetProportional(HUD2_TD[9], 1);
TextDrawSetSelectable(HUD2_TD[9], 0);

HUD2_TD[10] = TextDrawCreate(576.000000, 415.000000, "I");
TextDrawFont(HUD2_TD[10], 2);
TextDrawLetterSize(HUD2_TD[10], 0.329165, 1.499998);
TextDrawTextSize(HUD2_TD[10], 400.000000, 17.000000);
TextDrawSetOutline(HUD2_TD[10], 0);
TextDrawSetShadow(HUD2_TD[10], 0);
TextDrawAlignment(HUD2_TD[10], 1);
TextDrawColor(HUD2_TD[10], -1);
TextDrawBackgroundColor(HUD2_TD[10], 255);
TextDrawBoxColor(HUD2_TD[10], 50);
TextDrawUseBox(HUD2_TD[10], 0);
TextDrawSetProportional(HUD2_TD[10], 1);
TextDrawSetSelectable(HUD2_TD[10], 0);

HUD2_TD[11] = TextDrawCreate(574.500000, 423.000000, "-");
TextDrawFont(HUD2_TD[11], 1);
TextDrawLetterSize(HUD2_TD[11], 0.508333, 0.550000);
TextDrawTextSize(HUD2_TD[11], 400.000000, 17.000000);
TextDrawSetOutline(HUD2_TD[11], 0);
TextDrawSetShadow(HUD2_TD[11], 0);
TextDrawAlignment(HUD2_TD[11], 1);
TextDrawColor(HUD2_TD[11], -1);
TextDrawBackgroundColor(HUD2_TD[11], 255);
TextDrawBoxColor(HUD2_TD[11], 50);
TextDrawUseBox(HUD2_TD[11], 0);
TextDrawSetProportional(HUD2_TD[11], 1);
TextDrawSetSelectable(HUD2_TD[11], 0);

HUD2_TD[12] = TextDrawCreate(566.000000, 433.500000, "ld_dual:white");
TextDrawFont(HUD2_TD[12], 4);
TextDrawLetterSize(HUD2_TD[12], 0.600000, 2.000000);
TextDrawTextSize(HUD2_TD[12], 23.899999, 3.500000);
TextDrawSetOutline(HUD2_TD[12], 1);
TextDrawSetShadow(HUD2_TD[12], 0);
TextDrawAlignment(HUD2_TD[12], 1);
TextDrawColor(HUD2_TD[12], -1061109505);
TextDrawBackgroundColor(HUD2_TD[12], 255);
TextDrawBoxColor(HUD2_TD[12], 255);
TextDrawUseBox(HUD2_TD[12], 1);
TextDrawSetProportional(HUD2_TD[12], 1);
TextDrawSetSelectable(HUD2_TD[12], 0);


//Player Textdraws
	HUNGERBAR_2[playerid] = CreatePlayerTextDraw(playerid, 594.500000, 433.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HUNGERBAR_2[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HUNGERBAR_2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HUNGERBAR_2[playerid], 23.399999, 3.500000);
	PlayerTextDrawSetOutline(playerid, HUNGERBAR_2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HUNGERBAR_2[playerid], 0);
	PlayerTextDrawAlignment(playerid, HUNGERBAR_2[playerid], 1);
	PlayerTextDrawColor(playerid, HUNGERBAR_2[playerid], 852308735);
	PlayerTextDrawBackgroundColor(playerid, HUNGERBAR_2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HUNGERBAR_2[playerid], 255);
	PlayerTextDrawUseBox(playerid, HUNGERBAR_2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HUNGERBAR_2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HUNGERBAR_2[playerid], 0);

	THIRSTBAR_2[playerid] = CreatePlayerTextDraw(playerid, 566.000000, 433.500000, "ld_dual:white");
	PlayerTextDrawFont(playerid, THIRSTBAR_2[playerid], 4);
	PlayerTextDrawLetterSize(playerid, THIRSTBAR_2[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, THIRSTBAR_2[playerid], 23.899999, 3.500000);
	PlayerTextDrawSetOutline(playerid, THIRSTBAR_2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, THIRSTBAR_2[playerid], 0);
	PlayerTextDrawAlignment(playerid, THIRSTBAR_2[playerid], 1);
	PlayerTextDrawColor(playerid, THIRSTBAR_2[playerid], 1687547391);
	PlayerTextDrawBackgroundColor(playerid, THIRSTBAR_2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, THIRSTBAR_2[playerid], 255);
	PlayerTextDrawUseBox(playerid, THIRSTBAR_2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, THIRSTBAR_2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, THIRSTBAR_2[playerid], 0);

	SPEEDO_2[playerid] = CreatePlayerTextDraw(playerid, 559.000000, 418.000000, "Sultan I Julius Thurway South~n~Engine ON I Fuel: 100 I Health 100%");
	PlayerTextDrawFont(playerid, SPEEDO_2[playerid], 1);
	PlayerTextDrawLetterSize(playerid, SPEEDO_2[playerid], 0.162500, 1.000001);
	PlayerTextDrawTextSize(playerid, SPEEDO_2[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDO_2[playerid], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDO_2[playerid], 0);
	PlayerTextDrawAlignment(playerid, SPEEDO_2[playerid], 3);
	PlayerTextDrawColor(playerid, SPEEDO_2[playerid], -149);
	PlayerTextDrawBackgroundColor(playerid, SPEEDO_2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDO_2[playerid], 50);
	PlayerTextDrawUseBox(playerid, SPEEDO_2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDO_2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDO_2[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
