/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:SPEEDOTD[MAX_PLAYERS][5];

//Textdraws

//Player Textdraws
	SPEEDOTD[playerid][0] = CreatePlayerTextDraw(playerid, 533.000000, 401.000000, "100");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][0], 2);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][0], 0.450000, 2.449999);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][0], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][0], 0);

	SPEEDOTD[playerid][1] = CreatePlayerTextDraw(playerid, 533.000000, 390.000000, "Solair");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][1], 2);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][1], 0.229166, 1.250000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][1], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][1], 1433087999);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][1], 0);

	SPEEDOTD[playerid][2] = CreatePlayerTextDraw(playerid, 574.000000, 411.000000, "KM/H");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][2], 0.237500, 1.150000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][2], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][2], 0);

	SPEEDOTD[playerid][3] = CreatePlayerTextDraw(playerid, 572.000000, 399.000000, "1000.0");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][3], 0.237500, 1.150000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][3], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][3], 1433087999);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][3], 0);

	SPEEDOTD[playerid][4] = CreatePlayerTextDraw(playerid, 535.000000, 424.000000, "~r~LOCKED");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][4], 0.237500, 1.150000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][4], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][4], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
