/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:LOGOTD[3];

//Textdraws
LOGOTD[0] = TextDrawCreate(272.000000, 3.000000, "R");
TextDrawFont(LOGOTD[0], 0);
TextDrawLetterSize(LOGOTD[0], 0.770833, 2.399999);
TextDrawTextSize(LOGOTD[0], 400.000000, 17.000000);
TextDrawSetOutline(LOGOTD[0], 1);
TextDrawSetShadow(LOGOTD[0], 0);
TextDrawAlignment(LOGOTD[0], 1);
TextDrawColor(LOGOTD[0], -1);
TextDrawBackgroundColor(LOGOTD[0], 255);
TextDrawBoxColor(LOGOTD[0], 50);
TextDrawUseBox(LOGOTD[0], 0);
TextDrawSetProportional(LOGOTD[0], 1);
TextDrawSetSelectable(LOGOTD[0], 0);

LOGOTD[1] = TextDrawCreate(294.000000, 5.000000, "evitalize");
TextDrawFont(LOGOTD[1], 1);
TextDrawLetterSize(LOGOTD[1], 0.224999, 1.300001);
TextDrawTextSize(LOGOTD[1], 400.000000, 17.000000);
TextDrawSetOutline(LOGOTD[1], 0);
TextDrawSetShadow(LOGOTD[1], 0);
TextDrawAlignment(LOGOTD[1], 1);
TextDrawColor(LOGOTD[1], -16776961);
TextDrawBackgroundColor(LOGOTD[1], 255);
TextDrawBoxColor(LOGOTD[1], 50);
TextDrawUseBox(LOGOTD[1], 0);
TextDrawSetProportional(LOGOTD[1], 1);
TextDrawSetSelectable(LOGOTD[1], 0);

LOGOTD[2] = TextDrawCreate(294.000000, 16.000000, "Police Pursuit");
TextDrawFont(LOGOTD[2], 1);
TextDrawLetterSize(LOGOTD[2], 0.191666, 0.950001);
TextDrawTextSize(LOGOTD[2], 400.000000, 17.000000);
TextDrawSetOutline(LOGOTD[2], 0);
TextDrawSetShadow(LOGOTD[2], 0);
TextDrawAlignment(LOGOTD[2], 1);
TextDrawColor(LOGOTD[2], 65535);
TextDrawBackgroundColor(LOGOTD[2], 255);
TextDrawBoxColor(LOGOTD[2], 50);
TextDrawUseBox(LOGOTD[2], 0);
TextDrawSetProportional(LOGOTD[2], 1);
TextDrawSetSelectable(LOGOTD[2], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
