/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][7];
new PlayerText:PASSWORDTD[MAX_PLAYERS];
new PlayerText:LOGINTD[MAX_PLAYERS];
new PlayerText:PASSWORDTEXT[MAX_PLAYERS];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 258.000000, 148.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 115.500000, 201.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 136);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 258.000000, 148.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 115.500000, 13.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], 1687547391);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 276.000000, 173.000000, "Last Day on San Andreas");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.145833, 1.200000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 292.000000, 187.000000, "LOGIN PANEL");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.170833, 1.450000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 269.000000, 246.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 96.500000, 13.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 1687547391);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PASSWORDTD[playerid] = CreatePlayerTextDraw(playerid, 270.000000, 247.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PASSWORDTD[playerid], 4);
PlayerTextDrawLetterSize(playerid, PASSWORDTD[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PASSWORDTD[playerid], 94.599998, 11.000000);
PlayerTextDrawSetOutline(playerid, PASSWORDTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, PASSWORDTD[playerid], 0);
PlayerTextDrawAlignment(playerid, PASSWORDTD[playerid], 1);
PlayerTextDrawColor(playerid, PASSWORDTD[playerid], 9145343);
PlayerTextDrawBackgroundColor(playerid, PASSWORDTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, PASSWORDTD[playerid], 50);
PlayerTextDrawUseBox(playerid, PASSWORDTD[playerid], 1);
PlayerTextDrawSetProportional(playerid, PASSWORDTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, PASSWORDTD[playerid], 1);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 269.000000, 232.000000, "PASSWORD:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.150000, 1.200000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

LOGINTD[playerid] = CreatePlayerTextDraw(playerid, 283.000000, 297.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, LOGINTD[playerid], 4);
PlayerTextDrawLetterSize(playerid, LOGINTD[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, LOGINTD[playerid], 65.500000, 30.000000);
PlayerTextDrawSetOutline(playerid, LOGINTD[playerid], 1);
PlayerTextDrawSetShadow(playerid, LOGINTD[playerid], 0);
PlayerTextDrawAlignment(playerid, LOGINTD[playerid], 1);
PlayerTextDrawColor(playerid, LOGINTD[playerid], 1687547391);
PlayerTextDrawBackgroundColor(playerid, LOGINTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, LOGINTD[playerid], 50);
PlayerTextDrawUseBox(playerid, LOGINTD[playerid], 1);
PlayerTextDrawSetProportional(playerid, LOGINTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, LOGINTD[playerid], 1);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 298.000000, 304.000000, "LOGIN >>>");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.170833, 1.450000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

PASSWORDTEXT[playerid] = CreatePlayerTextDraw(playerid, 316.000000, 248.000000, "xxxxxxxxxxxxxxxx");
PlayerTextDrawFont(playerid, PASSWORDTEXT[playerid], 2);
PlayerTextDrawLetterSize(playerid, PASSWORDTEXT[playerid], 0.104166, 0.850000);
PlayerTextDrawTextSize(playerid, PASSWORDTEXT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PASSWORDTEXT[playerid], 0);
PlayerTextDrawSetShadow(playerid, PASSWORDTEXT[playerid], 0);
PlayerTextDrawAlignment(playerid, PASSWORDTEXT[playerid], 2);
PlayerTextDrawColor(playerid, PASSWORDTEXT[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, PASSWORDTEXT[playerid], 255);
PlayerTextDrawBoxColor(playerid, PASSWORDTEXT[playerid], 50);
PlayerTextDrawUseBox(playerid, PASSWORDTEXT[playerid], 0);
PlayerTextDrawSetProportional(playerid, PASSWORDTEXT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, PASSWORDTEXT[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
