/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:SETUPTD[MAX_PLAYERS][7];
new PlayerText:SETNAME[MAX_PLAYERS];
new PlayerText:SETORIGIN[MAX_PLAYERS];
new PlayerText:ORIGINTD[MAX_PLAYERS];
new PlayerText:SETGENDER[MAX_PLAYERS];
new PlayerText:GENDERTD[MAX_PLAYERS];
new PlayerText:FINISHSETUP[MAX_PLAYERS];
new PlayerText:SETBIRTHDATE[MAX_PLAYERS];
new PlayerText:BIRTHDATETD[MAX_PLAYERS];
new PlayerText:NAMETD[MAX_PLAYERS];

//Textdraws

//Player Textdraws
	SETUPTD[playerid][0] = CreatePlayerTextDraw(playerid, 325.000000, 131.000000, "_");
	PlayerTextDrawFont(playerid, SETUPTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, SETUPTD[playerid][0], 0.600000, 21.950008);
	PlayerTextDrawTextSize(playerid, SETUPTD[playerid][0], 293.500000, 178.500000);
	PlayerTextDrawSetOutline(playerid, SETUPTD[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, SETUPTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, SETUPTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, SETUPTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, SETUPTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, SETUPTD[playerid][0], -421070081);
	PlayerTextDrawUseBox(playerid, SETUPTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, SETUPTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, SETUPTD[playerid][0], 0);

	SETUPTD[playerid][1] = CreatePlayerTextDraw(playerid, 283.000000, 136.000000, "Character_Setup");
	PlayerTextDrawFont(playerid, SETUPTD[playerid][1], 2);
	PlayerTextDrawLetterSize(playerid, SETUPTD[playerid][1], 0.212500, 1.399999);
	PlayerTextDrawTextSize(playerid, SETUPTD[playerid][1], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SETUPTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, SETUPTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, SETUPTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, SETUPTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, SETUPTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, SETUPTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, SETUPTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, SETUPTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, SETUPTD[playerid][1], 0);

	SETNAME[playerid] = CreatePlayerTextDraw(playerid, 249.000000, 163.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SETNAME[playerid], 4);
	PlayerTextDrawLetterSize(playerid, SETNAME[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SETNAME[playerid], 150.000000, 18.500000);
	PlayerTextDrawSetOutline(playerid, SETNAME[playerid], 1);
	PlayerTextDrawSetShadow(playerid, SETNAME[playerid], 0);
	PlayerTextDrawAlignment(playerid, SETNAME[playerid], 1);
	PlayerTextDrawColor(playerid, SETNAME[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, SETNAME[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SETNAME[playerid], 50);
	PlayerTextDrawUseBox(playerid, SETNAME[playerid], 1);
	PlayerTextDrawSetProportional(playerid, SETNAME[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SETNAME[playerid], 1);

	SETORIGIN[playerid] = CreatePlayerTextDraw(playerid, 249.000000, 195.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SETORIGIN[playerid], 4);
	PlayerTextDrawLetterSize(playerid, SETORIGIN[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SETORIGIN[playerid], 150.000000, 18.500000);
	PlayerTextDrawSetOutline(playerid, SETORIGIN[playerid], 1);
	PlayerTextDrawSetShadow(playerid, SETORIGIN[playerid], 0);
	PlayerTextDrawAlignment(playerid, SETORIGIN[playerid], 1);
	PlayerTextDrawColor(playerid, SETORIGIN[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, SETORIGIN[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SETORIGIN[playerid], 50);
	PlayerTextDrawUseBox(playerid, SETORIGIN[playerid], 1);
	PlayerTextDrawSetProportional(playerid, SETORIGIN[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SETORIGIN[playerid], 1);

	SETUPTD[playerid][2] = CreatePlayerTextDraw(playerid, 258.000000, 197.000000, "ORIGIN:");
	PlayerTextDrawFont(playerid, SETUPTD[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, SETUPTD[playerid][2], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, SETUPTD[playerid][2], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SETUPTD[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, SETUPTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, SETUPTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, SETUPTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, SETUPTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, SETUPTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, SETUPTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, SETUPTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, SETUPTD[playerid][2], 0);

	ORIGINTD[playerid] = CreatePlayerTextDraw(playerid, 394.000000, 197.000000, "Unknown");
	PlayerTextDrawFont(playerid, ORIGINTD[playerid], 2);
	PlayerTextDrawLetterSize(playerid, ORIGINTD[playerid], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, ORIGINTD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, ORIGINTD[playerid], 0);
	PlayerTextDrawSetShadow(playerid, ORIGINTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, ORIGINTD[playerid], 3);
	PlayerTextDrawColor(playerid, ORIGINTD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, ORIGINTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ORIGINTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, ORIGINTD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ORIGINTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ORIGINTD[playerid], 0);

	SETGENDER[playerid] = CreatePlayerTextDraw(playerid, 249.000000, 227.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SETGENDER[playerid], 4);
	PlayerTextDrawLetterSize(playerid, SETGENDER[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SETGENDER[playerid], 150.000000, 18.500000);
	PlayerTextDrawSetOutline(playerid, SETGENDER[playerid], 1);
	PlayerTextDrawSetShadow(playerid, SETGENDER[playerid], 0);
	PlayerTextDrawAlignment(playerid, SETGENDER[playerid], 1);
	PlayerTextDrawColor(playerid, SETGENDER[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, SETGENDER[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SETGENDER[playerid], 50);
	PlayerTextDrawUseBox(playerid, SETGENDER[playerid], 1);
	PlayerTextDrawSetProportional(playerid, SETGENDER[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SETGENDER[playerid], 1);

	SETUPTD[playerid][3] = CreatePlayerTextDraw(playerid, 258.000000, 229.000000, "GENDER:");
	PlayerTextDrawFont(playerid, SETUPTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, SETUPTD[playerid][3], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, SETUPTD[playerid][3], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SETUPTD[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, SETUPTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, SETUPTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, SETUPTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, SETUPTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, SETUPTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, SETUPTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, SETUPTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, SETUPTD[playerid][3], 0);

	GENDERTD[playerid] = CreatePlayerTextDraw(playerid, 394.000000, 229.000000, "Unknown");
	PlayerTextDrawFont(playerid, GENDERTD[playerid], 2);
	PlayerTextDrawLetterSize(playerid, GENDERTD[playerid], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, GENDERTD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, GENDERTD[playerid], 0);
	PlayerTextDrawSetShadow(playerid, GENDERTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, GENDERTD[playerid], 3);
	PlayerTextDrawColor(playerid, GENDERTD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, GENDERTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, GENDERTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, GENDERTD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, GENDERTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, GENDERTD[playerid], 0);

	FINISHSETUP[playerid] = CreatePlayerTextDraw(playerid, 249.000000, 291.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, FINISHSETUP[playerid], 4);
	PlayerTextDrawLetterSize(playerid, FINISHSETUP[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, FINISHSETUP[playerid], 150.000000, 18.500000);
	PlayerTextDrawSetOutline(playerid, FINISHSETUP[playerid], 1);
	PlayerTextDrawSetShadow(playerid, FINISHSETUP[playerid], 0);
	PlayerTextDrawAlignment(playerid, FINISHSETUP[playerid], 1);
	PlayerTextDrawColor(playerid, FINISHSETUP[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, FINISHSETUP[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FINISHSETUP[playerid], 50);
	PlayerTextDrawUseBox(playerid, FINISHSETUP[playerid], 1);
	PlayerTextDrawSetProportional(playerid, FINISHSETUP[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FINISHSETUP[playerid], 1);

	SETUPTD[playerid][4] = CreatePlayerTextDraw(playerid, 304.000000, 293.000000, "Finish Setup");
	PlayerTextDrawFont(playerid, SETUPTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, SETUPTD[playerid][4], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, SETUPTD[playerid][4], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SETUPTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, SETUPTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, SETUPTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, SETUPTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, SETUPTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, SETUPTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, SETUPTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, SETUPTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, SETUPTD[playerid][4], 0);

	SETBIRTHDATE[playerid] = CreatePlayerTextDraw(playerid, 249.000000, 258.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SETBIRTHDATE[playerid], 4);
	PlayerTextDrawLetterSize(playerid, SETBIRTHDATE[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SETBIRTHDATE[playerid], 150.000000, 18.500000);
	PlayerTextDrawSetOutline(playerid, SETBIRTHDATE[playerid], 1);
	PlayerTextDrawSetShadow(playerid, SETBIRTHDATE[playerid], 0);
	PlayerTextDrawAlignment(playerid, SETBIRTHDATE[playerid], 1);
	PlayerTextDrawColor(playerid, SETBIRTHDATE[playerid], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, SETBIRTHDATE[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SETBIRTHDATE[playerid], 50);
	PlayerTextDrawUseBox(playerid, SETBIRTHDATE[playerid], 1);
	PlayerTextDrawSetProportional(playerid, SETBIRTHDATE[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SETBIRTHDATE[playerid], 1);

	BIRTHDATETD[playerid] = CreatePlayerTextDraw(playerid, 394.000000, 260.000000, "Unknown");
	PlayerTextDrawFont(playerid, BIRTHDATETD[playerid], 2);
	PlayerTextDrawLetterSize(playerid, BIRTHDATETD[playerid], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, BIRTHDATETD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, BIRTHDATETD[playerid], 0);
	PlayerTextDrawSetShadow(playerid, BIRTHDATETD[playerid], 0);
	PlayerTextDrawAlignment(playerid, BIRTHDATETD[playerid], 3);
	PlayerTextDrawColor(playerid, BIRTHDATETD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, BIRTHDATETD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BIRTHDATETD[playerid], 50);
	PlayerTextDrawUseBox(playerid, BIRTHDATETD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, BIRTHDATETD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BIRTHDATETD[playerid], 0);

	SETUPTD[playerid][5] = CreatePlayerTextDraw(playerid, 258.000000, 260.000000, "BIRTHDATE:");
	PlayerTextDrawFont(playerid, SETUPTD[playerid][5], 2);
	PlayerTextDrawLetterSize(playerid, SETUPTD[playerid][5], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, SETUPTD[playerid][5], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SETUPTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, SETUPTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, SETUPTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, SETUPTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, SETUPTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, SETUPTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, SETUPTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, SETUPTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, SETUPTD[playerid][5], 0);

	SETUPTD[playerid][6] = CreatePlayerTextDraw(playerid, 258.000000, 165.000000, "Name:");
	PlayerTextDrawFont(playerid, SETUPTD[playerid][6], 2);
	PlayerTextDrawLetterSize(playerid, SETUPTD[playerid][6], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, SETUPTD[playerid][6], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SETUPTD[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, SETUPTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, SETUPTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, SETUPTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, SETUPTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, SETUPTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, SETUPTD[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, SETUPTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, SETUPTD[playerid][6], 0);

	NAMETD[playerid] = CreatePlayerTextDraw(playerid, 394.000000, 166.000000, "Unknown");
	PlayerTextDrawFont(playerid, NAMETD[playerid], 2);
	PlayerTextDrawLetterSize(playerid, NAMETD[playerid], 0.158333, 1.250000);
	PlayerTextDrawTextSize(playerid, NAMETD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, NAMETD[playerid], 0);
	PlayerTextDrawSetShadow(playerid, NAMETD[playerid], 0);
	PlayerTextDrawAlignment(playerid, NAMETD[playerid], 3);
	PlayerTextDrawColor(playerid, NAMETD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, NAMETD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, NAMETD[playerid], 50);
	PlayerTextDrawUseBox(playerid, NAMETD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, NAMETD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, NAMETD[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
