/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][17];
new PlayerText:PISTOLBAR[MAX_PLAYERS];
new PlayerText:PISTOLAMOUNT[MAX_PLAYERS];
new PlayerText:SHOTGUNBAR[MAX_PLAYERS];
new PlayerText:SHOTGUNAMOUNT[MAX_PLAYERS];
new PlayerText:SMGBAR[MAX_PLAYERS];
new PlayerText:SMGAMOUNT[MAX_PLAYERS];
new PlayerText:RIFLEBAR[MAX_PLAYERS];
new PlayerText:RIFLEAMOUNT[MAX_PLAYERS];
new PlayerText:HIDESKILL[MAX_PLAYERS];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 326.000000, 171.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 16.300003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 298.500000, 240.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 1296911871);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 326.000000, 171.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 16.300003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 298.500000, 240.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 192);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 326.000000, 174.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 1.600003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 298.500000, 236.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], -764862721);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 284.000000, 173.000000, "Weapon Skills");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 3);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.320833, 1.649999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 326.000000, 200.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 1.600003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 298.500000, 236.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 1296911767);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 260.000000, 200.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 184.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

PISTOLBAR[playerid] = CreatePlayerTextDraw(playerid, 260.000000, 200.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PISTOLBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, PISTOLBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PISTOLBAR[playerid], 184.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, PISTOLBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, PISTOLBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, PISTOLBAR[playerid], 1);
PlayerTextDrawColor(playerid, PISTOLBAR[playerid], -1094795694);
PlayerTextDrawBackgroundColor(playerid, PISTOLBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, PISTOLBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, PISTOLBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, PISTOLBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, PISTOLBAR[playerid], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 216.000000, 200.000000, "Pistol");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.325000, 1.400000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

PISTOLAMOUNT[playerid] = CreatePlayerTextDraw(playerid, 343.000000, 201.000000, "999");
PlayerTextDrawFont(playerid, PISTOLAMOUNT[playerid], 1);
PlayerTextDrawLetterSize(playerid, PISTOLAMOUNT[playerid], 0.237500, 1.199999);
PlayerTextDrawTextSize(playerid, PISTOLAMOUNT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PISTOLAMOUNT[playerid], 0);
PlayerTextDrawSetShadow(playerid, PISTOLAMOUNT[playerid], 0);
PlayerTextDrawAlignment(playerid, PISTOLAMOUNT[playerid], 2);
PlayerTextDrawColor(playerid, PISTOLAMOUNT[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, PISTOLAMOUNT[playerid], 255);
PlayerTextDrawBoxColor(playerid, PISTOLAMOUNT[playerid], 50);
PlayerTextDrawUseBox(playerid, PISTOLAMOUNT[playerid], 0);
PlayerTextDrawSetProportional(playerid, PISTOLAMOUNT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, PISTOLAMOUNT[playerid], 0);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 326.000000, 226.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.600000, 1.600003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 298.500000, 236.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 1296911767);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 216.000000, 225.000000, "Shotgun");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.325000, 1.400000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 260.000000, 226.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 184.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

SHOTGUNBAR[playerid] = CreatePlayerTextDraw(playerid, 260.000000, 226.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, SHOTGUNBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, SHOTGUNBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, SHOTGUNBAR[playerid], 184.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, SHOTGUNBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, SHOTGUNBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, SHOTGUNBAR[playerid], 1);
PlayerTextDrawColor(playerid, SHOTGUNBAR[playerid], -1094795694);
PlayerTextDrawBackgroundColor(playerid, SHOTGUNBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, SHOTGUNBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, SHOTGUNBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, SHOTGUNBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SHOTGUNBAR[playerid], 0);

SHOTGUNAMOUNT[playerid] = CreatePlayerTextDraw(playerid, 343.000000, 227.000000, "999");
PlayerTextDrawFont(playerid, SHOTGUNAMOUNT[playerid], 1);
PlayerTextDrawLetterSize(playerid, SHOTGUNAMOUNT[playerid], 0.237500, 1.199999);
PlayerTextDrawTextSize(playerid, SHOTGUNAMOUNT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, SHOTGUNAMOUNT[playerid], 0);
PlayerTextDrawSetShadow(playerid, SHOTGUNAMOUNT[playerid], 0);
PlayerTextDrawAlignment(playerid, SHOTGUNAMOUNT[playerid], 2);
PlayerTextDrawColor(playerid, SHOTGUNAMOUNT[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, SHOTGUNAMOUNT[playerid], 255);
PlayerTextDrawBoxColor(playerid, SHOTGUNAMOUNT[playerid], 50);
PlayerTextDrawUseBox(playerid, SHOTGUNAMOUNT[playerid], 0);
PlayerTextDrawSetProportional(playerid, SHOTGUNAMOUNT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SHOTGUNAMOUNT[playerid], 0);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 326.000000, 253.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.600000, 1.600003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 298.500000, 236.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 1296911767);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 216.000000, 251.000000, "SMG");
PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.325000, 1.400000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 260.000000, 253.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 184.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][12], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

SMGBAR[playerid] = CreatePlayerTextDraw(playerid, 260.000000, 253.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, SMGBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, SMGBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, SMGBAR[playerid], 184.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, SMGBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, SMGBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, SMGBAR[playerid], 1);
PlayerTextDrawColor(playerid, SMGBAR[playerid], -1094795694);
PlayerTextDrawBackgroundColor(playerid, SMGBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, SMGBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, SMGBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, SMGBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SMGBAR[playerid], 0);

SMGAMOUNT[playerid] = CreatePlayerTextDraw(playerid, 343.000000, 254.000000, "999");
PlayerTextDrawFont(playerid, SMGAMOUNT[playerid], 1);
PlayerTextDrawLetterSize(playerid, SMGAMOUNT[playerid], 0.237500, 1.199999);
PlayerTextDrawTextSize(playerid, SMGAMOUNT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, SMGAMOUNT[playerid], 0);
PlayerTextDrawSetShadow(playerid, SMGAMOUNT[playerid], 0);
PlayerTextDrawAlignment(playerid, SMGAMOUNT[playerid], 2);
PlayerTextDrawColor(playerid, SMGAMOUNT[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, SMGAMOUNT[playerid], 255);
PlayerTextDrawBoxColor(playerid, SMGAMOUNT[playerid], 50);
PlayerTextDrawUseBox(playerid, SMGAMOUNT[playerid], 0);
PlayerTextDrawSetProportional(playerid, SMGAMOUNT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, SMGAMOUNT[playerid], 0);

PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 326.000000, 280.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.600000, 1.600003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 298.500000, 236.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 1296911767);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 218.000000, 279.000000, "Rifle");
PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.325000, 1.400000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);

PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 260.000000, 280.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 184.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][15], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);

RIFLEBAR[playerid] = CreatePlayerTextDraw(playerid, 260.000000, 279.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, RIFLEBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, RIFLEBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, RIFLEBAR[playerid], 184.000000, 14.000000);
PlayerTextDrawSetOutline(playerid, RIFLEBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, RIFLEBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, RIFLEBAR[playerid], 1);
PlayerTextDrawColor(playerid, RIFLEBAR[playerid], -1094795694);
PlayerTextDrawBackgroundColor(playerid, RIFLEBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, RIFLEBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, RIFLEBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, RIFLEBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, RIFLEBAR[playerid], 0);

RIFLEAMOUNT[playerid] = CreatePlayerTextDraw(playerid, 343.000000, 280.000000, "999");
PlayerTextDrawFont(playerid, RIFLEAMOUNT[playerid], 1);
PlayerTextDrawLetterSize(playerid, RIFLEAMOUNT[playerid], 0.237500, 1.199999);
PlayerTextDrawTextSize(playerid, RIFLEAMOUNT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, RIFLEAMOUNT[playerid], 0);
PlayerTextDrawSetShadow(playerid, RIFLEAMOUNT[playerid], 0);
PlayerTextDrawAlignment(playerid, RIFLEAMOUNT[playerid], 2);
PlayerTextDrawColor(playerid, RIFLEAMOUNT[playerid], 255);
PlayerTextDrawBackgroundColor(playerid, RIFLEAMOUNT[playerid], 255);
PlayerTextDrawBoxColor(playerid, RIFLEAMOUNT[playerid], 50);
PlayerTextDrawUseBox(playerid, RIFLEAMOUNT[playerid], 0);
PlayerTextDrawSetProportional(playerid, RIFLEAMOUNT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, RIFLEAMOUNT[playerid], 0);

PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 214.000000, 301.000000, "HINT: Go to Shooting Range to increase your skills!");
PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.141666, 1.350000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][16], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 0);

HIDESKILL[playerid] = CreatePlayerTextDraw(playerid, 435.000000, 172.000000, "X");
PlayerTextDrawFont(playerid, HIDESKILL[playerid], 1);
PlayerTextDrawLetterSize(playerid, HIDESKILL[playerid], 0.541666, 1.749999);
PlayerTextDrawTextSize(playerid, HIDESKILL[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, HIDESKILL[playerid], 0);
PlayerTextDrawSetShadow(playerid, HIDESKILL[playerid], 0);
PlayerTextDrawAlignment(playerid, HIDESKILL[playerid], 2);
PlayerTextDrawColor(playerid, HIDESKILL[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, HIDESKILL[playerid], 255);
PlayerTextDrawBoxColor(playerid, HIDESKILL[playerid], 50);
PlayerTextDrawUseBox(playerid, HIDESKILL[playerid], 0);
PlayerTextDrawSetProportional(playerid, HIDESKILL[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HIDESKILL[playerid], 1);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
