/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:SPEEDOTD[MAX_PLAYERS][7];
new PlayerText:KMHTD[MAX_PLAYERS];
new PlayerText:HEALTHBAR[MAX_PLAYERS];
new PlayerText:FUELBAR[MAX_PLAYERS];
new PlayerText:ENGINETD[MAX_PLAYERS];
new PlayerText:DOORTD[MAX_PLAYERS];

//Textdraws

//Player Textdraws
	SPEEDOTD[playerid][0] = CreatePlayerTextDraw(playerid, 147.000000, 362.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][0], 2.000000, 62.500000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][0], 0);

	KMHTD[playerid] = CreatePlayerTextDraw(playerid, 168.000000, 383.000000, "150");
	PlayerTextDrawFont(playerid, KMHTD[playerid], 2);
	PlayerTextDrawLetterSize(playerid, KMHTD[playerid], 0.358332, 1.750000);
	PlayerTextDrawTextSize(playerid, KMHTD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, KMHTD[playerid], 0);
	PlayerTextDrawSetShadow(playerid, KMHTD[playerid], 1);
	PlayerTextDrawAlignment(playerid, KMHTD[playerid], 2);
	PlayerTextDrawColor(playerid, KMHTD[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, KMHTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, KMHTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, KMHTD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, KMHTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, KMHTD[playerid], 0);

	SPEEDOTD[playerid][1] = CreatePlayerTextDraw(playerid, 188.000000, 388.000000, "KM/H");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][1], 2);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][1], 0.133332, 1.000000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][1], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][1], 1);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][1], 0);

	SPEEDOTD[playerid][2] = CreatePlayerTextDraw(playerid, 165.000000, 403.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][2], 50.000000, 7.500000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][2], 1296911771);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][2], 0);

	SPEEDOTD[playerid][3] = CreatePlayerTextDraw(playerid, 165.000000, 417.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][3], 50.000000, 7.500000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][3], 1296911771);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][3], 0);

	HEALTHBAR[playerid] = CreatePlayerTextDraw(playerid, 165.000000, 417.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, HEALTHBAR[playerid], 4);
	PlayerTextDrawLetterSize(playerid, HEALTHBAR[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, HEALTHBAR[playerid], 50.000000, 7.500000);
	PlayerTextDrawSetOutline(playerid, HEALTHBAR[playerid], 1);
	PlayerTextDrawSetShadow(playerid, HEALTHBAR[playerid], 0);
	PlayerTextDrawAlignment(playerid, HEALTHBAR[playerid], 1);
	PlayerTextDrawColor(playerid, HEALTHBAR[playerid], -741092453);
	PlayerTextDrawBackgroundColor(playerid, HEALTHBAR[playerid], 255);
	PlayerTextDrawBoxColor(playerid, HEALTHBAR[playerid], 50);
	PlayerTextDrawUseBox(playerid, HEALTHBAR[playerid], 1);
	PlayerTextDrawSetProportional(playerid, HEALTHBAR[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, HEALTHBAR[playerid], 0);

	FUELBAR[playerid] = CreatePlayerTextDraw(playerid, 165.000000, 403.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, FUELBAR[playerid], 4);
	PlayerTextDrawLetterSize(playerid, FUELBAR[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, FUELBAR[playerid], 50.000000, 7.500000);
	PlayerTextDrawSetOutline(playerid, FUELBAR[playerid], 1);
	PlayerTextDrawSetShadow(playerid, FUELBAR[playerid], 0);
	PlayerTextDrawAlignment(playerid, FUELBAR[playerid], 1);
	PlayerTextDrawColor(playerid, FUELBAR[playerid], 1687547291);
	PlayerTextDrawBackgroundColor(playerid, FUELBAR[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FUELBAR[playerid], 50);
	PlayerTextDrawUseBox(playerid, FUELBAR[playerid], 1);
	PlayerTextDrawSetProportional(playerid, FUELBAR[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FUELBAR[playerid], 0);

	SPEEDOTD[playerid][4] = CreatePlayerTextDraw(playerid, 152.000000, 415.000000, "VHP");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][4], 0.112499, 1.049999);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][4], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][4], 0);

	SPEEDOTD[playerid][5] = CreatePlayerTextDraw(playerid, 152.000000, 401.000000, "FUEL");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][5], 2);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][5], 0.112499, 1.049999);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][5], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][5], 0);

	SPEEDOTD[playerid][6] = CreatePlayerTextDraw(playerid, 149.000000, 381.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SPEEDOTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, SPEEDOTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SPEEDOTD[playerid][6], 47.000000, -1.500000);
	PlayerTextDrawSetOutline(playerid, SPEEDOTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, SPEEDOTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, SPEEDOTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, SPEEDOTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, SPEEDOTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, SPEEDOTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, SPEEDOTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, SPEEDOTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, SPEEDOTD[playerid][6], 0);

	ENGINETD[playerid] = CreatePlayerTextDraw(playerid, 153.000000, 369.000000, "ENGINE");
	PlayerTextDrawFont(playerid, ENGINETD[playerid], 1);
	PlayerTextDrawLetterSize(playerid, ENGINETD[playerid], 0.133332, 0.800000);
	PlayerTextDrawTextSize(playerid, ENGINETD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, ENGINETD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, ENGINETD[playerid], 0);
	PlayerTextDrawAlignment(playerid, ENGINETD[playerid], 1);
	PlayerTextDrawColor(playerid, ENGINETD[playerid], 852308735);
	PlayerTextDrawBackgroundColor(playerid, ENGINETD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ENGINETD[playerid], 50);
	PlayerTextDrawUseBox(playerid, ENGINETD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ENGINETD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ENGINETD[playerid], 0);

	DOORTD[playerid] = CreatePlayerTextDraw(playerid, 178.000000, 369.000000, "DOOR");
	PlayerTextDrawFont(playerid, DOORTD[playerid], 1);
	PlayerTextDrawLetterSize(playerid, DOORTD[playerid], 0.133332, 0.800000);
	PlayerTextDrawTextSize(playerid, DOORTD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, DOORTD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, DOORTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, DOORTD[playerid], 1);
	PlayerTextDrawColor(playerid, DOORTD[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, DOORTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, DOORTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, DOORTD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, DOORTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, DOORTD[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
