/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:TAXI_GUI[MAX_PLAYERS][14];

//Textdraws

//Player Textdraws
	TAXI_GUI[playerid][0] = CreatePlayerTextDraw(playerid, 504.000000, 261.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][0], 126.000000, 74.500000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][0], 1);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][0], 1296911871);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][0], 0);

	TAXI_GUI[playerid][1] = CreatePlayerTextDraw(playerid, 508.000000, 266.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][1], 118.000000, 65.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][1], 1);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][1], 255);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][1], 0);

	TAXI_GUI[playerid][2] = CreatePlayerTextDraw(playerid, 509.000000, 267.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][2], 116.000000, 63.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][2], 1);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][2], -741092353);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][2], 0);

	TAXI_GUI[playerid][3] = CreatePlayerTextDraw(playerid, 509.000000, 267.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][3], 116.000000, 63.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][3], 1);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][3], 1296911812);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][3], 0);

	TAXI_GUI[playerid][4] = CreatePlayerTextDraw(playerid, 508.000000, 291.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][4], 118.000000, 1.500000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][4], 1);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][4], 255);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][4], 0);

	TAXI_GUI[playerid][5] = CreatePlayerTextDraw(playerid, 540.000000, 266.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][5], 1.500000, 26.500000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][5], 1);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][5], 255);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][5], 0);

	TAXI_GUI[playerid][6] = CreatePlayerTextDraw(playerid, 518.000000, 271.000000, "ON");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][6], 1);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][6], 0.233332, 1.649999);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][6], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][6], 1);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][6], -1094795521);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][6], 0);

	TAXI_GUI[playerid][7] = CreatePlayerTextDraw(playerid, 620.000000, 270.000000, "$ 10000");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][7], 1);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][7], 0.266665, 1.549998);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][7], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][7], 3);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][7], 9109759);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][7], 0);

	TAXI_GUI[playerid][8] = CreatePlayerTextDraw(playerid, 572.000000, 281.000000, "Total price $");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][8], 1);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][8], 0.133332, 0.750000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][8], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][8], 3);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][8], 0);

	TAXI_GUI[playerid][9] = CreatePlayerTextDraw(playerid, 554.000000, 291.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][9], 1.500000, 39.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][9], 1);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][9], 255);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][9], 0);

	TAXI_GUI[playerid][10] = CreatePlayerTextDraw(playerid, 548.000000, 297.000000, "$ 2");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][10], 1);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][10], 0.362499, 1.899998);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][10], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][10], 3);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][10], 1687547391);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][10], 0);

	TAXI_GUI[playerid][11] = CreatePlayerTextDraw(playerid, 543.000000, 319.000000, "Price per 50m");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][11], 1);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][11], 0.133332, 0.750000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][11], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][11], 3);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][11], 0);

	TAXI_GUI[playerid][12] = CreatePlayerTextDraw(playerid, 619.000000, 297.000000, "0.0mi");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][12], 1);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][12], 0.295832, 1.799998);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][12], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][12], 0);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][12], 3);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][12], -764862721);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][12], 0);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][12], 0);

	TAXI_GUI[playerid][13] = CreatePlayerTextDraw(playerid, 620.000000, 319.000000, "Total distance");
	PlayerTextDrawFont(playerid, TAXI_GUI[playerid][13], 1);
	PlayerTextDrawLetterSize(playerid, TAXI_GUI[playerid][13], 0.133332, 0.750000);
	PlayerTextDrawTextSize(playerid, TAXI_GUI[playerid][13], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, TAXI_GUI[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, TAXI_GUI[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, TAXI_GUI[playerid][13], 3);
	PlayerTextDrawColor(playerid, TAXI_GUI[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, TAXI_GUI[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, TAXI_GUI[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, TAXI_GUI[playerid][13], 0);
	PlayerTextDrawSetProportional(playerid, TAXI_GUI[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, TAXI_GUI[playerid][13], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
