/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:LOGOTD[MAX_PLAYERS][3];
new PlayerText:TIMETD[MAX_PLAYERS];

//Textdraws

//Player Textdraws
TIMETD[playerid] = CreatePlayerTextDraw(playerid, 548.000000, 25.000000, "02:03:59");
PlayerTextDrawFont(playerid, TIMETD[playerid], 1);
PlayerTextDrawLetterSize(playerid, TIMETD[playerid], 0.337500, 1.200000);
PlayerTextDrawTextSize(playerid, TIMETD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, TIMETD[playerid], 1);
PlayerTextDrawSetShadow(playerid, TIMETD[playerid], 0);
PlayerTextDrawAlignment(playerid, TIMETD[playerid], 1);
PlayerTextDrawColor(playerid, TIMETD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, TIMETD[playerid], 255);
PlayerTextDrawBoxColor(playerid, TIMETD[playerid], 50);
PlayerTextDrawUseBox(playerid, TIMETD[playerid], 0);
PlayerTextDrawSetProportional(playerid, TIMETD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, TIMETD[playerid], 0);

LOGOTD[playerid][0] = CreatePlayerTextDraw(playerid, 276.000000, 9.000000, "~r~Revitalize");
PlayerTextDrawFont(playerid, LOGOTD[playerid][0], 0);
PlayerTextDrawLetterSize(playerid, LOGOTD[playerid][0], 0.312500, 1.400002);
PlayerTextDrawTextSize(playerid, LOGOTD[playerid][0], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, LOGOTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, LOGOTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, LOGOTD[playerid][0], 1);
PlayerTextDrawColor(playerid, LOGOTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, LOGOTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, LOGOTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, LOGOTD[playerid][0], 0);
PlayerTextDrawSetProportional(playerid, LOGOTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, LOGOTD[playerid][0], 0);

LOGOTD[playerid][1] = CreatePlayerTextDraw(playerid, 317.000000, 9.000000, "Roleplay");
PlayerTextDrawFont(playerid, LOGOTD[playerid][1], 0);
PlayerTextDrawLetterSize(playerid, LOGOTD[playerid][1], 0.312500, 1.400002);
PlayerTextDrawTextSize(playerid, LOGOTD[playerid][1], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, LOGOTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, LOGOTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, LOGOTD[playerid][1], 1);
PlayerTextDrawColor(playerid, LOGOTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, LOGOTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, LOGOTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, LOGOTD[playerid][1], 0);
PlayerTextDrawSetProportional(playerid, LOGOTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, LOGOTD[playerid][1], 0);

LOGOTD[playerid][2] = CreatePlayerTextDraw(playerid, 301.000000, 24.000000, "v3.2b consistent");
PlayerTextDrawFont(playerid, LOGOTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, LOGOTD[playerid][2], 0.145833, 0.850001);
PlayerTextDrawTextSize(playerid, LOGOTD[playerid][2], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, LOGOTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, LOGOTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, LOGOTD[playerid][2], 1);
PlayerTextDrawColor(playerid, LOGOTD[playerid][2], -1094795521);
PlayerTextDrawBackgroundColor(playerid, LOGOTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, LOGOTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, LOGOTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, LOGOTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, LOGOTD[playerid][2], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
