/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:TOUR_GUI[5];

//Textdraws
TOUR_GUI[0] = TextDrawCreate(264.000000, 29.000000, "ld_dual:white");
TextDrawFont(TOUR_GUI[0], 4);
TextDrawLetterSize(TOUR_GUI[0], 0.600000, 2.000000);
TextDrawTextSize(TOUR_GUI[0], 104.500000, 17.000000);
TextDrawSetOutline(TOUR_GUI[0], 1);
TextDrawSetShadow(TOUR_GUI[0], 0);
TextDrawAlignment(TOUR_GUI[0], 1);
TextDrawColor(TOUR_GUI[0], -1094795647);
TextDrawBackgroundColor(TOUR_GUI[0], 255);
TextDrawBoxColor(TOUR_GUI[0], 50);
TextDrawUseBox(TOUR_GUI[0], 1);
TextDrawSetProportional(TOUR_GUI[0], 1);
TextDrawSetSelectable(TOUR_GUI[0], 0);

TOUR_GUI[1] = TextDrawCreate(292.000000, 29.000000, "ld_dual:white");
TextDrawFont(TOUR_GUI[1], 4);
TextDrawLetterSize(TOUR_GUI[1], 0.600000, 2.000000);
TextDrawTextSize(TOUR_GUI[1], 49.000000, 17.000000);
TextDrawSetOutline(TOUR_GUI[1], 1);
TextDrawSetShadow(TOUR_GUI[1], 0);
TextDrawAlignment(TOUR_GUI[1], 1);
TextDrawColor(TOUR_GUI[1], -16777083);
TextDrawBackgroundColor(TOUR_GUI[1], 255);
TextDrawBoxColor(TOUR_GUI[1], 50);
TextDrawUseBox(TOUR_GUI[1], 1);
TextDrawSetProportional(TOUR_GUI[1], 1);
TextDrawSetSelectable(TOUR_GUI[1], 0);

TOUR_GUI[2] = TextDrawCreate(317.000000, 30.000000, "10:00");
TextDrawFont(TOUR_GUI[2], 1);
TextDrawLetterSize(TOUR_GUI[2], 0.300000, 1.500000);
TextDrawTextSize(TOUR_GUI[2], 400.000000, 17.000000);
TextDrawSetOutline(TOUR_GUI[2], 1);
TextDrawSetShadow(TOUR_GUI[2], 0);
TextDrawAlignment(TOUR_GUI[2], 2);
TextDrawColor(TOUR_GUI[2], -1);
TextDrawBackgroundColor(TOUR_GUI[2], 255);
TextDrawBoxColor(TOUR_GUI[2], 50);
TextDrawUseBox(TOUR_GUI[2], 0);
TextDrawSetProportional(TOUR_GUI[2], 1);
TextDrawSetSelectable(TOUR_GUI[2], 0);

TOUR_GUI[3] = TextDrawCreate(278.000000, 30.000000, "100");
TextDrawFont(TOUR_GUI[3], 1);
TextDrawLetterSize(TOUR_GUI[3], 0.300000, 1.500000);
TextDrawTextSize(TOUR_GUI[3], 400.000000, 17.000000);
TextDrawSetOutline(TOUR_GUI[3], 0);
TextDrawSetShadow(TOUR_GUI[3], 0);
TextDrawAlignment(TOUR_GUI[3], 2);
TextDrawColor(TOUR_GUI[3], -1);
TextDrawBackgroundColor(TOUR_GUI[3], 255);
TextDrawBoxColor(TOUR_GUI[3], 50);
TextDrawUseBox(TOUR_GUI[3], 0);
TextDrawSetProportional(TOUR_GUI[3], 1);
TextDrawSetSelectable(TOUR_GUI[3], 0);

TOUR_GUI[4] = TextDrawCreate(354.000000, 30.000000, "20");
TextDrawFont(TOUR_GUI[4], 1);
TextDrawLetterSize(TOUR_GUI[4], 0.300000, 1.500000);
TextDrawTextSize(TOUR_GUI[4], 400.000000, 17.000000);
TextDrawSetOutline(TOUR_GUI[4], 0);
TextDrawSetShadow(TOUR_GUI[4], 0);
TextDrawAlignment(TOUR_GUI[4], 2);
TextDrawColor(TOUR_GUI[4], -1);
TextDrawBackgroundColor(TOUR_GUI[4], 255);
TextDrawBoxColor(TOUR_GUI[4], 50);
TextDrawUseBox(TOUR_GUI[4], 0);
TextDrawSetProportional(TOUR_GUI[4], 1);
TextDrawSetSelectable(TOUR_GUI[4], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
