/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][20];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 569.000000, 169.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 27.249988);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 298.500000, 121.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 230);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 569.000000, 169.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.450011);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 298.500000, 121.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], -1962934017);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 530.000000, 174.000000, "UnderGround_Roleplay");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.212499, 1.300000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 515.000000, 202.000000, "Select_your_character:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 516.000000, 215.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 107.000000, 13.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], 1296911750);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 1);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 568.000000, 216.000000, "Cyrill_Sylvestre");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 516.000000, 239.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 107.000000, 13.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 1296911750);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 1);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 568.000000, 240.000000, "Cyrill_Sylvestre");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 516.000000, 262.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 107.000000, 13.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], 1296911750);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 1);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 568.000000, 263.000000, "Cyrill_Sylvestre");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 515.000000, 286.000000, "Character_Information:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 516.000000, 300.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 107.000000, 45.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][11], 1296911750);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 519.000000, 302.000000, "Name:_Cyrill_Sylvestre");
PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][12], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 519.000000, 312.000000, "Date_of_Birth:_09/12/1999");
PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 519.000000, 322.000000, "Origin:_Mexico");
PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);

PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 519.000000, 332.000000, "Last_Location:_Ganton");
PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][15], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);

PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 516.000000, 368.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 107.000000, 13.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][16], 1296911750);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 1);

PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 568.000000, 369.000000, "Create_Character");
PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][17], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 0);

PlayerTD[playerid][18] = CreatePlayerTextDraw(playerid, 516.000000, 389.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][18], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][18], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][18], 107.000000, 13.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][18], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][18], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][18], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][18], 1296911750);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][18], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][18], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][18], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][18], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][18], 1);

PlayerTD[playerid][19] = CreatePlayerTextDraw(playerid, 568.000000, 390.000000, "Spawn_Character");
PlayerTextDrawFont(playerid, PlayerTD[playerid][19], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][19], 0.137500, 0.950000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][19], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][19], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][19], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][19], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][19], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][19], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][19], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][19], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][19], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][19], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
