/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][18];
new PlayerText:DONEJOB[MAX_PLAYERS];
new PlayerText:BURGERTD[MAX_PLAYERS];
new PlayerText:PIZZATD[MAX_PLAYERS];
new PlayerText:COLATD[MAX_PLAYERS];
new PlayerText:SPRUNKTD[MAX_PLAYERS];
new PlayerText:FOODTD[MAX_PLAYERS];
new PlayerText:DRINKTD[MAX_PLAYERS];
new PlayerText:RESETJOB[MAX_PLAYERS];
new PlayerText:EXITJOB[MAX_PLAYERS];
new PlayerText:DONEFOOD[MAX_PLAYERS];
new PlayerText:DONEDRINK[MAX_PLAYERS];

//Textdraws
	DONEJOB[playerid] = CreatePlayerTextDraw(playerid, 364.000000, 384.000000, "ld_dual:white");
	PlayerTextDrawFont(DONEJOB[playerid], 4);
	PlayerTextDrawLetterSize(DONEJOB[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(DONEJOB[playerid], 32.000000, 17.000000);
	PlayerTextDrawSetOutline(DONEJOB[playerid], 1);
	PlayerTextDrawSetShadow(DONEJOB[playerid], 0);
	PlayerTextDrawAlignment(DONEJOB[playerid], 1);
	PlayerTextDrawColor(DONEJOB[playerid], 16711935);
	PlayerTextDrawBackgroundColor(DONEJOB[playerid], 255);
	PlayerTextDrawBoxColor(DONEJOB[playerid], 50);
	PlayerTextDrawUseBox(DONEJOB[playerid], 1);
	PlayerTextDrawSetProportional(DONEJOB[playerid], 1);
	PlayerTextDrawSetSelectable(DONEJOB[playerid], 1);


	//Player Textdraws
	PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 350.000000, 352.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 10.300003);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 333.500000, 255.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 135);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

	PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 183.000000, 352.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 10.300003);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 333.500000, 72.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], -1378294017);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

	PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 232.000000, 357.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 53.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 1687547391);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

	PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 240.000000, 357.000000, "FOOD");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.325000, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

	BURGERTD[playerid] = CreatePlayerTextDraw(playerid, 232.000000, 384.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, BURGERTD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, BURGERTD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, BURGERTD[playerid], 53.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, BURGERTD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, BURGERTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, BURGERTD[playerid], 1);
	PlayerTextDrawColor(playerid, BURGERTD[playerid], -764862721);
	PlayerTextDrawBackgroundColor(playerid, BURGERTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, BURGERTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, BURGERTD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, BURGERTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, BURGERTD[playerid], 1);

	PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 240.000000, 384.000000, "BURGER");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.233333, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

	PIZZATD[playerid] = CreatePlayerTextDraw(playerid, 232.000000, 411.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PIZZATD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, PIZZATD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PIZZATD[playerid], 53.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PIZZATD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, PIZZATD[playerid], 0);
	PlayerTextDrawAlignment(playerid, PIZZATD[playerid], 1);
	PlayerTextDrawColor(playerid, PIZZATD[playerid], -764862721);
	PlayerTextDrawBackgroundColor(playerid, PIZZATD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, PIZZATD[playerid], 50);
	PlayerTextDrawUseBox(playerid, PIZZATD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, PIZZATD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, PIZZATD[playerid], 1);

	PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 243.000000, 411.000000, "PIZZA");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.233333, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

	PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 297.000000, 357.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 53.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 1687547391);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

	PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 304.000000, 357.000000, "DRINK");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.325000, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

	COLATD[playerid] = CreatePlayerTextDraw(playerid, 297.000000, 384.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, COLATD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, COLATD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, COLATD[playerid], 53.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, COLATD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, COLATD[playerid], 0);
	PlayerTextDrawAlignment(playerid, COLATD[playerid], 1);
	PlayerTextDrawColor(playerid, COLATD[playerid], -764862721);
	PlayerTextDrawBackgroundColor(playerid, COLATD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, COLATD[playerid], 50);
	PlayerTextDrawUseBox(playerid, COLATD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, COLATD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, COLATD[playerid], 1);

	PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 308.000000, 384.000000, "COLA");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.270833, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

	SPRUNKTD[playerid] = CreatePlayerTextDraw(playerid, 297.000000, 411.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, SPRUNKTD[playerid], 4);
	PlayerTextDrawLetterSize(playerid, SPRUNKTD[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, SPRUNKTD[playerid], 53.500000, 17.000000);
	PlayerTextDrawSetOutline(playerid, SPRUNKTD[playerid], 1);
	PlayerTextDrawSetShadow(playerid, SPRUNKTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, SPRUNKTD[playerid], 1);
	PlayerTextDrawColor(playerid, SPRUNKTD[playerid], -764862721);
	PlayerTextDrawBackgroundColor(playerid, SPRUNKTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, SPRUNKTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, SPRUNKTD[playerid], 1);
	PlayerTextDrawSetProportional(playerid, SPRUNKTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, SPRUNKTD[playerid], 1);

	PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 303.000000, 411.000000, "SPRUNK");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.270833, 1.600000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

	PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 441.000000, 352.000000, "_");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.600000, 10.300003);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 333.500000, 72.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 2);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], -1378294017);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

	PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 156.000000, 356.000000, "ORDER MENU");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.241666, 1.399999);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

	FOODTD[playerid] = CreatePlayerTextDraw(playerid, 156.000000, 380.000000, "-_FOOD");
	PlayerTextDrawFont(playerid, FOODTD[playerid], 1);
	PlayerTextDrawLetterSize(playerid, FOODTD[playerid], 0.241666, 1.399999);
	PlayerTextDrawTextSize(playerid, FOODTD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, FOODTD[playerid], 0);
	PlayerTextDrawSetShadow(playerid, FOODTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, FOODTD[playerid], 1);
	PlayerTextDrawColor(playerid, FOODTD[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, FOODTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, FOODTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, FOODTD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, FOODTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, FOODTD[playerid], 0);

	DRINKTD[playerid] = CreatePlayerTextDraw(playerid, 156.000000, 398.000000, "-_DRINK");
	PlayerTextDrawFont(playerid, DRINKTD[playerid], 1);
	PlayerTextDrawLetterSize(playerid, DRINKTD[playerid], 0.241666, 1.399999);
	PlayerTextDrawTextSize(playerid, DRINKTD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, DRINKTD[playerid], 0);
	PlayerTextDrawSetShadow(playerid, DRINKTD[playerid], 0);
	PlayerTextDrawAlignment(playerid, DRINKTD[playerid], 1);
	PlayerTextDrawColor(playerid, DRINKTD[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, DRINKTD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, DRINKTD[playerid], 50);
	PlayerTextDrawUseBox(playerid, DRINKTD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, DRINKTD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, DRINKTD[playerid], 0);

	PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 154.000000, 370.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 57.500000, 1.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

	RESETJOB[playerid] = CreatePlayerTextDraw(playerid, 364.000000, 411.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, RESETJOB[playerid], 4);
	PlayerTextDrawLetterSize(playerid, RESETJOB[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, RESETJOB[playerid], 32.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, RESETJOB[playerid], 1);
	PlayerTextDrawSetShadow(playerid, RESETJOB[playerid], 0);
	PlayerTextDrawAlignment(playerid, RESETJOB[playerid], 1);
	PlayerTextDrawColor(playerid, RESETJOB[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, RESETJOB[playerid], 255);
	PlayerTextDrawBoxColor(playerid, RESETJOB[playerid], 50);
	PlayerTextDrawUseBox(playerid, RESETJOB[playerid], 1);
	PlayerTextDrawSetProportional(playerid, RESETJOB[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, RESETJOB[playerid], 1);

	PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 368.000000, 413.000000, "RESET");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.183333, 1.250000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

	PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 370.000000, 386.000000, "DONE");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.183333, 1.250000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);

	EXITJOB[playerid] = CreatePlayerTextDraw(playerid, 364.000000, 358.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, EXITJOB[playerid], 4);
	PlayerTextDrawLetterSize(playerid, EXITJOB[playerid], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EXITJOB[playerid], 32.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EXITJOB[playerid], 1);
	PlayerTextDrawSetShadow(playerid, EXITJOB[playerid], 0);
	PlayerTextDrawAlignment(playerid, EXITJOB[playerid], 1);
	PlayerTextDrawColor(playerid, EXITJOB[playerid], -16776961);
	PlayerTextDrawBackgroundColor(playerid, EXITJOB[playerid], 255);
	PlayerTextDrawBoxColor(playerid, EXITJOB[playerid], 50);
	PlayerTextDrawUseBox(playerid, EXITJOB[playerid], 1);
	PlayerTextDrawSetProportional(playerid, EXITJOB[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, EXITJOB[playerid], 1);

	PlayerTD[playerid][15] = CreatePlayerTextDraw(playerid, 372.000000, 360.000000, "EXIT");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][15], 2);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][15], 0.183333, 1.250000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][15], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][15], -1);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][15], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][15], 0);

	PlayerTD[playerid][16] = CreatePlayerTextDraw(playerid, 415.000000, 356.000000, "ORDER_DONE");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][16], 0.241666, 1.399999);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][16], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][16], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][16], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][16], 0);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][16], 0);

	PlayerTD[playerid][17] = CreatePlayerTextDraw(playerid, 412.000000, 370.000000, "ld_dual:white");
	PlayerTextDrawFont(playerid, PlayerTD[playerid][17], 4);
	PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][17], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, PlayerTD[playerid][17], 57.500000, 1.000000);
	PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawColor(playerid, PlayerTD[playerid][17], 255);
	PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][17], 50);
	PlayerTextDrawUseBox(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][17], 0);

	DONEFOOD[playerid] = CreatePlayerTextDraw(playerid, 412.000000, 380.000000, "-_FOOD");
	PlayerTextDrawFont(playerid, DONEFOOD[playerid], 1);
	PlayerTextDrawLetterSize(playerid, DONEFOOD[playerid], 0.241666, 1.399999);
	PlayerTextDrawTextSize(playerid, DONEFOOD[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, DONEFOOD[playerid], 0);
	PlayerTextDrawSetShadow(playerid, DONEFOOD[playerid], 0);
	PlayerTextDrawAlignment(playerid, DONEFOOD[playerid], 1);
	PlayerTextDrawColor(playerid, DONEFOOD[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, DONEFOOD[playerid], 255);
	PlayerTextDrawBoxColor(playerid, DONEFOOD[playerid], 50);
	PlayerTextDrawUseBox(playerid, DONEFOOD[playerid], 0);
	PlayerTextDrawSetProportional(playerid, DONEFOOD[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, DONEFOOD[playerid], 0);

	DONEDRINK[playerid] = CreatePlayerTextDraw(playerid, 412.000000, 398.000000, "-_DRINK");
	PlayerTextDrawFont(playerid, DONEDRINK[playerid], 1);
	PlayerTextDrawLetterSize(playerid, DONEDRINK[playerid], 0.241666, 1.399999);
	PlayerTextDrawTextSize(playerid, DONEDRINK[playerid], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, DONEDRINK[playerid], 0);
	PlayerTextDrawSetShadow(playerid, DONEDRINK[playerid], 0);
	PlayerTextDrawAlignment(playerid, DONEDRINK[playerid], 1);
	PlayerTextDrawColor(playerid, DONEDRINK[playerid], 255);
	PlayerTextDrawBackgroundColor(playerid, DONEDRINK[playerid], 255);
	PlayerTextDrawBoxColor(playerid, DONEDRINK[playerid], 50);
	PlayerTextDrawUseBox(playerid, DONEDRINK[playerid], 0);
	PlayerTextDrawSetProportional(playerid, DONEDRINK[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, DONEDRINK[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
