/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][15];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 550.000000, 154.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.649999, 27.300003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 298.500000, 115.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 135);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 550.000000, 154.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.649999, 4.500008);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 298.500000, 115.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], -1061109625);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 550.000000, 157.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.649999, 3.800005);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 298.500000, 109.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 204);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 514.000000, 160.000000, "Gunsmith");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.629166, 2.449999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 550.000000, 222.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.649999, -0.349992);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 298.500000, 115.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], -1061109625);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 494.000000, 232.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 113.000000, 16.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], 151);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 494.000000, 257.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 113.000000, 16.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], 151);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 501.000000, 236.000000, "Antler_Knife_($40.00)");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.187500, 0.849999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 501.000000, 260.000000, "FN_Mle_1903_($275.00)");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.187500, 0.849999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 494.000000, 281.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 113.000000, 16.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], 151);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 501.000000, 284.000000, "Winchester_1897_($358.00)");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.187500, 0.849999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 494.000000, 308.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 113.000000, 16.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][11], 151);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 501.000000, 311.000000, "Carcano_Rifle_($556.00)");
PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.187500, 0.849999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][12], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 494.000000, 374.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 113.000000, 16.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][13], 151);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);

PlayerTD[playerid][14] = CreatePlayerTextDraw(playerid, 501.000000, 377.000000, "Close");
PlayerTextDrawFont(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][14], 0.187500, 0.849999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][14], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][14], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][14], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][14], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][14], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][14], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][14], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
