/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][14];
new PlayerText:WEPNAMETD[MAX_PLAYERS];
new PlayerText:WHPTD[MAX_PLAYERS];
new PlayerText:AMMOTD[MAX_PLAYERS];
new PlayerText:DOLLARTD[MAX_PLAYERS];
new PlayerText:HPBAR[MAX_PLAYERS];
new PlayerText:APBAR[MAX_PLAYERS];
new PlayerText:HUNGERBAR[MAX_PLAYERS];
new PlayerText:THIRSTBAR[MAX_PLAYERS];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 553.000000, 16.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 10.300003);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 298.500000, 140.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 1296911871);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 553.000000, 19.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.554166, 9.650000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 291.500000, 135.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], -741092353);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 553.000000, 20.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 9.349999);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 298.500000, 133.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 1296911871);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

WEPNAMETD[playerid] = CreatePlayerTextDraw(playerid, 553.000000, 22.000000, "AK-47");
PlayerTextDrawFont(playerid, WEPNAMETD[playerid], 2);
PlayerTextDrawLetterSize(playerid, WEPNAMETD[playerid], 0.175000, 1.500000);
PlayerTextDrawTextSize(playerid, WEPNAMETD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, WEPNAMETD[playerid], 0);
PlayerTextDrawSetShadow(playerid, WEPNAMETD[playerid], 0);
PlayerTextDrawAlignment(playerid, WEPNAMETD[playerid], 2);
PlayerTextDrawColor(playerid, WEPNAMETD[playerid], -1094795568);
PlayerTextDrawBackgroundColor(playerid, WEPNAMETD[playerid], 255);
PlayerTextDrawBoxColor(playerid, WEPNAMETD[playerid], 50);
PlayerTextDrawUseBox(playerid, WEPNAMETD[playerid], 0);
PlayerTextDrawSetProportional(playerid, WEPNAMETD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, WEPNAMETD[playerid], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 553.000000, 43.000000, "_");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, -0.400000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 298.500000, 118.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 2);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 1296911871);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], -741092353);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

WHPTD[playerid] = CreatePlayerTextDraw(playerid, 602.000000, 22.000000, "100.0");
PlayerTextDrawFont(playerid, WHPTD[playerid], 2);
PlayerTextDrawLetterSize(playerid, WHPTD[playerid], 0.175000, 1.500000);
PlayerTextDrawTextSize(playerid, WHPTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, WHPTD[playerid], 0);
PlayerTextDrawSetShadow(playerid, WHPTD[playerid], 0);
PlayerTextDrawAlignment(playerid, WHPTD[playerid], 3);
PlayerTextDrawColor(playerid, WHPTD[playerid], -1094795568);
PlayerTextDrawBackgroundColor(playerid, WHPTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, WHPTD[playerid], 50);
PlayerTextDrawUseBox(playerid, WHPTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, WHPTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, WHPTD[playerid], 0);

AMMOTD[playerid] = CreatePlayerTextDraw(playerid, 491.000000, 22.000000, "999");
PlayerTextDrawFont(playerid, AMMOTD[playerid], 2);
PlayerTextDrawLetterSize(playerid, AMMOTD[playerid], 0.175000, 1.500000);
PlayerTextDrawTextSize(playerid, AMMOTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, AMMOTD[playerid], 0);
PlayerTextDrawSetShadow(playerid, AMMOTD[playerid], 0);
PlayerTextDrawAlignment(playerid, AMMOTD[playerid], 1);
PlayerTextDrawColor(playerid, AMMOTD[playerid], -1094795568);
PlayerTextDrawBackgroundColor(playerid, AMMOTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, AMMOTD[playerid], 50);
PlayerTextDrawUseBox(playerid, AMMOTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, AMMOTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, AMMOTD[playerid], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 613.000000, 27.000000, "WHP");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.112500, 0.800001);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 3);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1094795568);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 520.000000, 27.000000, "AMMO");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.112500, 0.800001);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 3);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1094795568);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);

DOLLARTD[playerid] = CreatePlayerTextDraw(playerid, 614.000000, 46.000000, "$100.00,0");
PlayerTextDrawFont(playerid, DOLLARTD[playerid], 2);
PlayerTextDrawLetterSize(playerid, DOLLARTD[playerid], 0.150000, 1.300001);
PlayerTextDrawTextSize(playerid, DOLLARTD[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, DOLLARTD[playerid], 0);
PlayerTextDrawSetShadow(playerid, DOLLARTD[playerid], 0);
PlayerTextDrawAlignment(playerid, DOLLARTD[playerid], 3);
PlayerTextDrawColor(playerid, DOLLARTD[playerid], 2094792898);
PlayerTextDrawBackgroundColor(playerid, DOLLARTD[playerid], 255);
PlayerTextDrawBoxColor(playerid, DOLLARTD[playerid], 50);
PlayerTextDrawUseBox(playerid, DOLLARTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, DOLLARTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, DOLLARTD[playerid], 0);

PlayerTD[playerid][6] = CreatePlayerTextDraw(playerid, 507.000000, 48.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][6], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][6], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][6], 52.000000, 7.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][6], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][6], -1061109616);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][6], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][6], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][6], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][6], 0);

PlayerTD[playerid][7] = CreatePlayerTextDraw(playerid, 492.000000, 45.000000, "HP:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][7], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][7], 0.150000, 1.300001);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][7], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][7], -741092353);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][7], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][7], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][7], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][7], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][7], 0);

HPBAR[playerid] = CreatePlayerTextDraw(playerid, 507.000000, 48.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HPBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, HPBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HPBAR[playerid], 52.000000, 7.500000);
PlayerTextDrawSetOutline(playerid, HPBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, HPBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, HPBAR[playerid], 1);
PlayerTextDrawColor(playerid, HPBAR[playerid], -16777072);
PlayerTextDrawBackgroundColor(playerid, HPBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, HPBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, HPBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, HPBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HPBAR[playerid], 0);

PlayerTD[playerid][8] = CreatePlayerTextDraw(playerid, 492.000000, 57.000000, "AP:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][8], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][8], 0.150000, 1.300001);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][8], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][8], -741092353);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][8], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][8], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][8], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][8], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][8], 0);

PlayerTD[playerid][9] = CreatePlayerTextDraw(playerid, 507.000000, 60.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][9], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][9], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][9], 52.000000, 7.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][9], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][9], -1061109616);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][9], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][9], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][9], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][9], 0);

APBAR[playerid] = CreatePlayerTextDraw(playerid, 507.000000, 60.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, APBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, APBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, APBAR[playerid], 52.000000, 7.500000);
PlayerTextDrawSetOutline(playerid, APBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, APBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, APBAR[playerid], 1);
PlayerTextDrawColor(playerid, APBAR[playerid], -1378294128);
PlayerTextDrawBackgroundColor(playerid, APBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, APBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, APBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, APBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, APBAR[playerid], 0);

PlayerTD[playerid][10] = CreatePlayerTextDraw(playerid, 492.000000, 77.000000, "HU:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][10], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][10], 0.150000, 1.300001);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][10], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][10], -741092353);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][10], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][10], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][10], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][10], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][10], 0);

PlayerTD[playerid][11] = CreatePlayerTextDraw(playerid, 507.000000, 80.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][11], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][11], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][11], 52.000000, 7.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][11], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][11], -1061109616);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][11], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][11], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][11], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][11], 0);

HUNGERBAR[playerid] = CreatePlayerTextDraw(playerid, 507.000000, 80.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HUNGERBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, HUNGERBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HUNGERBAR[playerid], 52.000000, 7.500000);
PlayerTextDrawSetOutline(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, HUNGERBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawColor(playerid, HUNGERBAR[playerid], -764862832);
PlayerTextDrawBackgroundColor(playerid, HUNGERBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, HUNGERBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HUNGERBAR[playerid], 0);

PlayerTD[playerid][12] = CreatePlayerTextDraw(playerid, 507.000000, 91.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][12], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][12], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][12], 52.000000, 7.500000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][12], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][12], -1061109616);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][12], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][12], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][12], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][12], 0);

THIRSTBAR[playerid] = CreatePlayerTextDraw(playerid, 507.000000, 91.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, THIRSTBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, THIRSTBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, THIRSTBAR[playerid], 52.000000, 7.500000);
PlayerTextDrawSetOutline(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, THIRSTBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawColor(playerid, THIRSTBAR[playerid], 1687547280);
PlayerTextDrawBackgroundColor(playerid, THIRSTBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, THIRSTBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, THIRSTBAR[playerid], 0);

PlayerTD[playerid][13] = CreatePlayerTextDraw(playerid, 492.000000, 88.000000, "TH:");
PlayerTextDrawFont(playerid, PlayerTD[playerid][13], 2);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][13], 0.150000, 1.300001);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][13], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][13], -741092353);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][13], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][13], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][13], 0);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][13], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][13], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
