/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:PlayerTD[MAX_PLAYERS][6];
new PlayerText:HUNGERBAR[MAX_PLAYERS];
new PlayerText:THIRSTBAR[MAX_PLAYERS];

//Textdraws

//Player Textdraws
PlayerTD[playerid][0] = CreatePlayerTextDraw(playerid, 163.000000, 395.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][0], 22.500000, 24.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][0], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][0], 171);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][0], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][0], 0);

PlayerTD[playerid][1] = CreatePlayerTextDraw(playerid, 166.000000, 399.000000, "HUD:radar_burgershot");
PlayerTextDrawFont(playerid, PlayerTD[playerid][1], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][1], 17.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][1], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][1], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][1], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][1], 0);

PlayerTD[playerid][2] = CreatePlayerTextDraw(playerid, 163.000000, 419.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][2], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][2], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][2], 22.500000, 3.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][2], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][2], -1094795605);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][2], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][2], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][2], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][2], 0);

HUNGERBAR[playerid] = CreatePlayerTextDraw(playerid, 163.000000, 419.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HUNGERBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, HUNGERBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HUNGERBAR[playerid], 22.500000, 3.000000);
PlayerTextDrawSetOutline(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, HUNGERBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawColor(playerid, HUNGERBAR[playerid], 16711851);
PlayerTextDrawBackgroundColor(playerid, HUNGERBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, HUNGERBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HUNGERBAR[playerid], 0);

PlayerTD[playerid][3] = CreatePlayerTextDraw(playerid, 163.000000, 353.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][3], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][3], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][3], 22.500000, 24.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][3], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][3], 171);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][3], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][3], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][3], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][3], 0);

PlayerTD[playerid][4] = CreatePlayerTextDraw(playerid, 163.000000, 377.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, PlayerTD[playerid][4], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][4], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][4], 22.500000, 3.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][4], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][4], -1094795605);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][4], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][4], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][4], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][4], 0);

THIRSTBAR[playerid] = CreatePlayerTextDraw(playerid, 163.000000, 377.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, THIRSTBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, THIRSTBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, THIRSTBAR[playerid], 22.500000, 3.000000);
PlayerTextDrawSetOutline(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, THIRSTBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawColor(playerid, THIRSTBAR[playerid], 16711851);
PlayerTextDrawBackgroundColor(playerid, THIRSTBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, THIRSTBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, THIRSTBAR[playerid], 0);

PlayerTD[playerid][5] = CreatePlayerTextDraw(playerid, 166.500000, 356.000000, "HUD:radar_diner");
PlayerTextDrawFont(playerid, PlayerTD[playerid][5], 4);
PlayerTextDrawLetterSize(playerid, PlayerTD[playerid][5], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, PlayerTD[playerid][5], 17.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetShadow(playerid, PlayerTD[playerid][5], 0);
PlayerTextDrawAlignment(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawColor(playerid, PlayerTD[playerid][5], -1);
PlayerTextDrawBackgroundColor(playerid, PlayerTD[playerid][5], 255);
PlayerTextDrawBoxColor(playerid, PlayerTD[playerid][5], 50);
PlayerTextDrawUseBox(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetProportional(playerid, PlayerTD[playerid][5], 1);
PlayerTextDrawSetSelectable(playerid, PlayerTD[playerid][5], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
