/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:HBEGUI[MAX_PLAYERS][2];
new PlayerText:HEALTHBAR[MAX_PLAYERS];
new PlayerText:ARMORBAR[MAX_PLAYERS];
new PlayerText:ARMORAMOUNT[MAX_PLAYERS];
new PlayerText:THIRSTBAR[MAX_PLAYERS];
new PlayerText:THIRSTAMOUNT[MAX_PLAYERS];
new PlayerText:HUNGERBAR[MAX_PLAYERS];
new PlayerText:HUNGERAMOUNT[MAX_PLAYERS];

//Textdraws

//Player Textdraws
HBEGUI[playerid][0] = CreatePlayerTextDraw(playerid, 529.000000, 432.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HBEGUI[playerid][0], 4);
PlayerTextDrawLetterSize(playerid, HBEGUI[playerid][0], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HBEGUI[playerid][0], 97.500000, 8.000000);
PlayerTextDrawSetOutline(playerid, HBEGUI[playerid][0], 1);
PlayerTextDrawSetShadow(playerid, HBEGUI[playerid][0], 0);
PlayerTextDrawAlignment(playerid, HBEGUI[playerid][0], 1);
PlayerTextDrawColor(playerid, HBEGUI[playerid][0], 1296911871);
PlayerTextDrawBackgroundColor(playerid, HBEGUI[playerid][0], 255);
PlayerTextDrawBoxColor(playerid, HBEGUI[playerid][0], 50);
PlayerTextDrawUseBox(playerid, HBEGUI[playerid][0], 1);
PlayerTextDrawSetProportional(playerid, HBEGUI[playerid][0], 1);
PlayerTextDrawSetSelectable(playerid, HBEGUI[playerid][0], 0);

HEALTHBAR[playerid] = CreatePlayerTextDraw(playerid, 533.000000, 435.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HEALTHBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, HEALTHBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HEALTHBAR[playerid], 90.500000, 3.000000);
PlayerTextDrawSetOutline(playerid, HEALTHBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, HEALTHBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, HEALTHBAR[playerid], 1);
PlayerTextDrawColor(playerid, HEALTHBAR[playerid], -16777012);
PlayerTextDrawBackgroundColor(playerid, HEALTHBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, HEALTHBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, HEALTHBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, HEALTHBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HEALTHBAR[playerid], 0);

HBEGUI[playerid][1] = CreatePlayerTextDraw(playerid, 529.000000, 403.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HBEGUI[playerid][1], 4);
PlayerTextDrawLetterSize(playerid, HBEGUI[playerid][1], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HBEGUI[playerid][1], 65.000000, 29.000000);
PlayerTextDrawSetOutline(playerid, HBEGUI[playerid][1], 1);
PlayerTextDrawSetShadow(playerid, HBEGUI[playerid][1], 0);
PlayerTextDrawAlignment(playerid, HBEGUI[playerid][1], 1);
PlayerTextDrawColor(playerid, HBEGUI[playerid][1], 1296911871);
PlayerTextDrawBackgroundColor(playerid, HBEGUI[playerid][1], 255);
PlayerTextDrawBoxColor(playerid, HBEGUI[playerid][1], 50);
PlayerTextDrawUseBox(playerid, HBEGUI[playerid][1], 1);
PlayerTextDrawSetProportional(playerid, HBEGUI[playerid][1], 1);
PlayerTextDrawSetSelectable(playerid, HBEGUI[playerid][1], 0);

ARMORBAR[playerid] = CreatePlayerTextDraw(playerid, 550.000000, 427.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, ARMORBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, ARMORBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, ARMORBAR[playerid], 38.000000, 3.000000);
PlayerTextDrawSetOutline(playerid, ARMORBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, ARMORBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, ARMORBAR[playerid], 1);
PlayerTextDrawColor(playerid, ARMORBAR[playerid], -52);
PlayerTextDrawBackgroundColor(playerid, ARMORBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, ARMORBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, ARMORBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, ARMORBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, ARMORBAR[playerid], 0);

ARMORAMOUNT[playerid] = CreatePlayerTextDraw(playerid, 540.000000, 425.000000, "0%");
PlayerTextDrawFont(playerid, ARMORAMOUNT[playerid], 1);
PlayerTextDrawLetterSize(playerid, ARMORAMOUNT[playerid], 0.137500, 0.650000);
PlayerTextDrawTextSize(playerid, ARMORAMOUNT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, ARMORAMOUNT[playerid], 0);
PlayerTextDrawSetShadow(playerid, ARMORAMOUNT[playerid], 0);
PlayerTextDrawAlignment(playerid, ARMORAMOUNT[playerid], 2);
PlayerTextDrawColor(playerid, ARMORAMOUNT[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, ARMORAMOUNT[playerid], 255);
PlayerTextDrawBoxColor(playerid, ARMORAMOUNT[playerid], 50);
PlayerTextDrawUseBox(playerid, ARMORAMOUNT[playerid], 0);
PlayerTextDrawSetProportional(playerid, ARMORAMOUNT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, ARMORAMOUNT[playerid], 0);

THIRSTBAR[playerid] = CreatePlayerTextDraw(playerid, 550.000000, 418.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, THIRSTBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, THIRSTBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, THIRSTBAR[playerid], 38.000000, 3.000000);
PlayerTextDrawSetOutline(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, THIRSTBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawColor(playerid, THIRSTBAR[playerid], 1687547340);
PlayerTextDrawBackgroundColor(playerid, THIRSTBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, THIRSTBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, THIRSTBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, THIRSTBAR[playerid], 0);

THIRSTAMOUNT[playerid] = CreatePlayerTextDraw(playerid, 540.000000, 416.000000, "0%");
PlayerTextDrawFont(playerid, THIRSTAMOUNT[playerid], 1);
PlayerTextDrawLetterSize(playerid, THIRSTAMOUNT[playerid], 0.137500, 0.650000);
PlayerTextDrawTextSize(playerid, THIRSTAMOUNT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, THIRSTAMOUNT[playerid], 0);
PlayerTextDrawSetShadow(playerid, THIRSTAMOUNT[playerid], 0);
PlayerTextDrawAlignment(playerid, THIRSTAMOUNT[playerid], 2);
PlayerTextDrawColor(playerid, THIRSTAMOUNT[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, THIRSTAMOUNT[playerid], 255);
PlayerTextDrawBoxColor(playerid, THIRSTAMOUNT[playerid], 50);
PlayerTextDrawUseBox(playerid, THIRSTAMOUNT[playerid], 0);
PlayerTextDrawSetProportional(playerid, THIRSTAMOUNT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, THIRSTAMOUNT[playerid], 0);

HUNGERBAR[playerid] = CreatePlayerTextDraw(playerid, 550.000000, 409.000000, "ld_dual:white");
PlayerTextDrawFont(playerid, HUNGERBAR[playerid], 4);
PlayerTextDrawLetterSize(playerid, HUNGERBAR[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, HUNGERBAR[playerid], 38.000000, 3.000000);
PlayerTextDrawSetOutline(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetShadow(playerid, HUNGERBAR[playerid], 0);
PlayerTextDrawAlignment(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawColor(playerid, HUNGERBAR[playerid], -2686772);
PlayerTextDrawBackgroundColor(playerid, HUNGERBAR[playerid], 255);
PlayerTextDrawBoxColor(playerid, HUNGERBAR[playerid], 50);
PlayerTextDrawUseBox(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetProportional(playerid, HUNGERBAR[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HUNGERBAR[playerid], 0);

HUNGERAMOUNT[playerid] = CreatePlayerTextDraw(playerid, 540.000000, 407.000000, "0%");
PlayerTextDrawFont(playerid, HUNGERAMOUNT[playerid], 1);
PlayerTextDrawLetterSize(playerid, HUNGERAMOUNT[playerid], 0.137500, 0.650000);
PlayerTextDrawTextSize(playerid, HUNGERAMOUNT[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, HUNGERAMOUNT[playerid], 0);
PlayerTextDrawSetShadow(playerid, HUNGERAMOUNT[playerid], 0);
PlayerTextDrawAlignment(playerid, HUNGERAMOUNT[playerid], 2);
PlayerTextDrawColor(playerid, HUNGERAMOUNT[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, HUNGERAMOUNT[playerid], 255);
PlayerTextDrawBoxColor(playerid, HUNGERAMOUNT[playerid], 50);
PlayerTextDrawUseBox(playerid, HUNGERAMOUNT[playerid], 0);
PlayerTextDrawSetProportional(playerid, HUNGERAMOUNT[playerid], 1);
PlayerTextDrawSetSelectable(playerid, HUNGERAMOUNT[playerid], 0);


/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
