#include <YSI_Coding\y_hooks>

new PlayerText:INV_TD[MAX_PLAYERS][8],
    PlayerText:INV_MODEL[MAX_PLAYERS][12],
    PlayerText:INV_SELECT[MAX_PLAYERS][12],
    PlayerText:INV_AMOUNT[MAX_PLAYERS][12],
    PlayerText:INV_NAME[MAX_PLAYERS][12],
    PlayerText:INV_INPUT[MAX_PLAYERS],
    PlayerText:INV_INPUT_NUM[MAX_PLAYERS],
    PlayerText:INV_PREV[MAX_PLAYERS],
    PlayerText:INV_NEXT[MAX_PLAYERS],
    PlayerText:INV_TITLE[MAX_PLAYERS],
    PlayerText:INV_GIVE[MAX_PLAYERS],
    PlayerText:INV_EXIT[MAX_PLAYERS],
    PlayerText:INV_USE[MAX_PLAYERS];

hook OnPlayerConnect(playerid) {
    INV_TD[playerid][0] = CreatePlayerTextDraw(playerid, 315.299987, 139.000000, "_");
    PlayerTextDrawFont(playerid, INV_TD[playerid][0], 1);
    PlayerTextDrawLetterSize(playerid, INV_TD[playerid][0], 0.600000, 25.850002);
    PlayerTextDrawTextSize(playerid, INV_TD[playerid][0], 251.000000, 160.000000);
    PlayerTextDrawSetOutline(playerid, INV_TD[playerid][0], 1);
    PlayerTextDrawSetShadow(playerid, INV_TD[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, INV_TD[playerid][0], 2);
    PlayerTextDrawColor(playerid, INV_TD[playerid][0], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_TD[playerid][0], 255);
    PlayerTextDrawBoxColor(playerid, INV_TD[playerid][0], 757935524);
    PlayerTextDrawUseBox(playerid, INV_TD[playerid][0], 1);
    PlayerTextDrawSetProportional(playerid, INV_TD[playerid][0], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TD[playerid][0], 0);

    INV_TD[playerid][1] = CreatePlayerTextDraw(playerid, 234.000000, 364.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_TD[playerid][1], 4);
    PlayerTextDrawLetterSize(playerid, INV_TD[playerid][1], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_TD[playerid][1], 162.500000, 22.000000);
    PlayerTextDrawSetOutline(playerid, INV_TD[playerid][1], 1);
    PlayerTextDrawSetShadow(playerid, INV_TD[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, INV_TD[playerid][1], 1);
    PlayerTextDrawColor(playerid, INV_TD[playerid][1], 757935580);
    PlayerTextDrawBackgroundColor(playerid, INV_TD[playerid][1], 255);
    PlayerTextDrawBoxColor(playerid, INV_TD[playerid][1], 50);
    PlayerTextDrawUseBox(playerid, INV_TD[playerid][1], 1);
    PlayerTextDrawSetProportional(playerid, INV_TD[playerid][1], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TD[playerid][1], 0);

    INV_TD[playerid][2] = CreatePlayerTextDraw(playerid, 234.000000, 125.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_TD[playerid][2], 4);
    PlayerTextDrawLetterSize(playerid, INV_TD[playerid][2], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_TD[playerid][2], 162.500000, 25.000000);
    PlayerTextDrawSetOutline(playerid, INV_TD[playerid][2], 1);
    PlayerTextDrawSetShadow(playerid, INV_TD[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, INV_TD[playerid][2], 1);
    PlayerTextDrawColor(playerid, INV_TD[playerid][2], -1709565953);
    PlayerTextDrawBackgroundColor(playerid, INV_TD[playerid][2], 255);
    PlayerTextDrawBoxColor(playerid, INV_TD[playerid][2], 50);
    PlayerTextDrawUseBox(playerid, INV_TD[playerid][2], 1);
    PlayerTextDrawSetProportional(playerid, INV_TD[playerid][2], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TD[playerid][2], 0);

    INV_EXIT[playerid] = CreatePlayerTextDraw(playerid, 374.000000, 129.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_EXIT[playerid], 4);
    PlayerTextDrawLetterSize(playerid, INV_EXIT[playerid], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_EXIT[playerid], 16.500000, 16.500000);
    PlayerTextDrawSetOutline(playerid, INV_EXIT[playerid], 1);
    PlayerTextDrawSetShadow(playerid, INV_EXIT[playerid], 0);
    PlayerTextDrawAlignment(playerid, INV_EXIT[playerid], 1);
    PlayerTextDrawColor(playerid, INV_EXIT[playerid], 255);
    PlayerTextDrawBackgroundColor(playerid, INV_EXIT[playerid], 255);
    PlayerTextDrawBoxColor(playerid, INV_EXIT[playerid], 50);
    PlayerTextDrawUseBox(playerid, INV_EXIT[playerid], 1);
    PlayerTextDrawSetProportional(playerid, INV_EXIT[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, INV_EXIT[playerid], 1);

    INV_TD[playerid][3] = CreatePlayerTextDraw(playerid, 379.000000, 131.000000, "X");
    PlayerTextDrawFont(playerid, INV_TD[playerid][3], 2);
    PlayerTextDrawLetterSize(playerid, INV_TD[playerid][3], 0.237499, 1.100000);
    PlayerTextDrawTextSize(playerid, INV_TD[playerid][3], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_TD[playerid][3], 0);
    PlayerTextDrawSetShadow(playerid, INV_TD[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, INV_TD[playerid][3], 1);
    PlayerTextDrawColor(playerid, INV_TD[playerid][3], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_TD[playerid][3], 255);
    PlayerTextDrawBoxColor(playerid, INV_TD[playerid][3], 50);
    PlayerTextDrawUseBox(playerid, INV_TD[playerid][3], 0);
    PlayerTextDrawSetProportional(playerid, INV_TD[playerid][3], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TD[playerid][3], 0);

    INV_TITLE[playerid] = CreatePlayerTextDraw(playerid, 241.000000, 134.000000, "_");
    PlayerTextDrawFont(playerid, INV_TITLE[playerid], 1);
    PlayerTextDrawLetterSize(playerid, INV_TITLE[playerid], 0.195833, 0.900000);
    PlayerTextDrawTextSize(playerid, INV_TITLE[playerid], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_TITLE[playerid], 0);
    PlayerTextDrawSetShadow(playerid, INV_TITLE[playerid], 0);
    PlayerTextDrawAlignment(playerid, INV_TITLE[playerid], 1);
    PlayerTextDrawColor(playerid, INV_TITLE[playerid], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_TITLE[playerid], 255);
    PlayerTextDrawBoxColor(playerid, INV_TITLE[playerid], 50);
    PlayerTextDrawUseBox(playerid, INV_TITLE[playerid], 0);
    PlayerTextDrawSetProportional(playerid, INV_TITLE[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TITLE[playerid], 0);

    INV_USE[playerid] = CreatePlayerTextDraw(playerid, 301.000000, 368.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_USE[playerid], 4);
    PlayerTextDrawLetterSize(playerid, INV_USE[playerid], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_USE[playerid], 27.000000, 12.000000);
    PlayerTextDrawSetOutline(playerid, INV_USE[playerid], 1);
    PlayerTextDrawSetShadow(playerid, INV_USE[playerid], 0);
    PlayerTextDrawAlignment(playerid, INV_USE[playerid], 1);
    PlayerTextDrawColor(playerid, INV_USE[playerid], -741092517);
    PlayerTextDrawBackgroundColor(playerid, INV_USE[playerid], 255);
    PlayerTextDrawBoxColor(playerid, INV_USE[playerid], 50);
    PlayerTextDrawUseBox(playerid, INV_USE[playerid], 1);
    PlayerTextDrawSetProportional(playerid, INV_USE[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, INV_USE[playerid], 1);

    INV_TD[playerid][4] = CreatePlayerTextDraw(playerid, 308.500000, 370.500000, "USE");
    PlayerTextDrawFont(playerid, INV_TD[playerid][4], 1);
    PlayerTextDrawLetterSize(playerid, INV_TD[playerid][4], 0.154165, 0.699999);
    PlayerTextDrawTextSize(playerid, INV_TD[playerid][4], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_TD[playerid][4], 0);
    PlayerTextDrawSetShadow(playerid, INV_TD[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, INV_TD[playerid][4], 1);
    PlayerTextDrawColor(playerid, INV_TD[playerid][4], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_TD[playerid][4], 255);
    PlayerTextDrawBoxColor(playerid, INV_TD[playerid][4], 50);
    PlayerTextDrawUseBox(playerid, INV_TD[playerid][4], 0);
    PlayerTextDrawSetProportional(playerid, INV_TD[playerid][4], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TD[playerid][4], 0);

    INV_PREV[playerid] = CreatePlayerTextDraw(playerid, 241.000000, 368.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_PREV[playerid], 4);
    PlayerTextDrawLetterSize(playerid, INV_PREV[playerid], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_PREV[playerid], 27.000000, 12.000000);
    PlayerTextDrawSetOutline(playerid, INV_PREV[playerid], 1);
    PlayerTextDrawSetShadow(playerid, INV_PREV[playerid], 0);
    PlayerTextDrawAlignment(playerid, INV_PREV[playerid], 1);
    PlayerTextDrawColor(playerid, INV_PREV[playerid], -741092517);
    PlayerTextDrawBackgroundColor(playerid, INV_PREV[playerid], 255);
    PlayerTextDrawBoxColor(playerid, INV_PREV[playerid], 50);
    PlayerTextDrawUseBox(playerid, INV_PREV[playerid], 1);
    PlayerTextDrawSetProportional(playerid, INV_PREV[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, INV_PREV[playerid], 1);

    INV_TD[playerid][5] = CreatePlayerTextDraw(playerid, 249.500000, 370.500000, "<<");
    PlayerTextDrawFont(playerid, INV_TD[playerid][5], 1);
    PlayerTextDrawLetterSize(playerid, INV_TD[playerid][5], 0.154165, 0.699999);
    PlayerTextDrawTextSize(playerid, INV_TD[playerid][5], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_TD[playerid][5], 0);
    PlayerTextDrawSetShadow(playerid, INV_TD[playerid][5], 0);
    PlayerTextDrawAlignment(playerid, INV_TD[playerid][5], 1);
    PlayerTextDrawColor(playerid, INV_TD[playerid][5], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_TD[playerid][5], 255);
    PlayerTextDrawBoxColor(playerid, INV_TD[playerid][5], 50);
    PlayerTextDrawUseBox(playerid, INV_TD[playerid][5], 0);
    PlayerTextDrawSetProportional(playerid, INV_TD[playerid][5], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TD[playerid][5], 0);

    INV_NEXT[playerid] = CreatePlayerTextDraw(playerid, 362.000000, 368.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_NEXT[playerid], 4);
    PlayerTextDrawLetterSize(playerid, INV_NEXT[playerid], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_NEXT[playerid], 27.000000, 12.000000);
    PlayerTextDrawSetOutline(playerid, INV_NEXT[playerid], 1);
    PlayerTextDrawSetShadow(playerid, INV_NEXT[playerid], 0);
    PlayerTextDrawAlignment(playerid, INV_NEXT[playerid], 1);
    PlayerTextDrawColor(playerid, INV_NEXT[playerid], -741092517);
    PlayerTextDrawBackgroundColor(playerid, INV_NEXT[playerid], 255);
    PlayerTextDrawBoxColor(playerid, INV_NEXT[playerid], 50);
    PlayerTextDrawUseBox(playerid, INV_NEXT[playerid], 1);
    PlayerTextDrawSetProportional(playerid, INV_NEXT[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NEXT[playerid], 1);

    INV_TD[playerid][6] = CreatePlayerTextDraw(playerid, 371.500000, 370.500000, ">>");
    PlayerTextDrawFont(playerid, INV_TD[playerid][6], 1);
    PlayerTextDrawLetterSize(playerid, INV_TD[playerid][6], 0.154165, 0.699999);
    PlayerTextDrawTextSize(playerid, INV_TD[playerid][6], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_TD[playerid][6], 0);
    PlayerTextDrawSetShadow(playerid, INV_TD[playerid][6], 0);
    PlayerTextDrawAlignment(playerid, INV_TD[playerid][6], 1);
    PlayerTextDrawColor(playerid, INV_TD[playerid][6], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_TD[playerid][6], 255);
    PlayerTextDrawBoxColor(playerid, INV_TD[playerid][6], 50);
    PlayerTextDrawUseBox(playerid, INV_TD[playerid][6], 0);
    PlayerTextDrawSetProportional(playerid, INV_TD[playerid][6], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TD[playerid][6], 0);

    INV_GIVE[playerid] = CreatePlayerTextDraw(playerid, 271.000000, 368.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_GIVE[playerid], 4);
    PlayerTextDrawLetterSize(playerid, INV_GIVE[playerid], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_GIVE[playerid], 27.000000, 12.000000);
    PlayerTextDrawSetOutline(playerid, INV_GIVE[playerid], 1);
    PlayerTextDrawSetShadow(playerid, INV_GIVE[playerid], 0);
    PlayerTextDrawAlignment(playerid, INV_GIVE[playerid], 1);
    PlayerTextDrawColor(playerid, INV_GIVE[playerid], -741092517);
    PlayerTextDrawBackgroundColor(playerid, INV_GIVE[playerid], 255);
    PlayerTextDrawBoxColor(playerid, INV_GIVE[playerid], 50);
    PlayerTextDrawUseBox(playerid, INV_GIVE[playerid], 1);
    PlayerTextDrawSetProportional(playerid, INV_GIVE[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, INV_GIVE[playerid], 1);

    INV_TD[playerid][7] = CreatePlayerTextDraw(playerid, 278.500000, 370.500000, "GIVE");
    PlayerTextDrawFont(playerid, INV_TD[playerid][7], 1);
    PlayerTextDrawLetterSize(playerid, INV_TD[playerid][7], 0.154165, 0.699999);
    PlayerTextDrawTextSize(playerid, INV_TD[playerid][7], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_TD[playerid][7], 0);
    PlayerTextDrawSetShadow(playerid, INV_TD[playerid][7], 0);
    PlayerTextDrawAlignment(playerid, INV_TD[playerid][7], 1);
    PlayerTextDrawColor(playerid, INV_TD[playerid][7], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_TD[playerid][7], 255);
    PlayerTextDrawBoxColor(playerid, INV_TD[playerid][7], 50);
    PlayerTextDrawUseBox(playerid, INV_TD[playerid][7], 0);
    PlayerTextDrawSetProportional(playerid, INV_TD[playerid][7], 1);
    PlayerTextDrawSetSelectable(playerid, INV_TD[playerid][7], 0);

    INV_INPUT[playerid] = CreatePlayerTextDraw(playerid, 332.000000, 368.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_INPUT[playerid], 4);
    PlayerTextDrawLetterSize(playerid, INV_INPUT[playerid], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_INPUT[playerid], 27.000000, 12.000000);
    PlayerTextDrawSetOutline(playerid, INV_INPUT[playerid], 1);
    PlayerTextDrawSetShadow(playerid, INV_INPUT[playerid], 0);
    PlayerTextDrawAlignment(playerid, INV_INPUT[playerid], 1);
    PlayerTextDrawColor(playerid, INV_INPUT[playerid], -741092517);
    PlayerTextDrawBackgroundColor(playerid, INV_INPUT[playerid], 255);
    PlayerTextDrawBoxColor(playerid, INV_INPUT[playerid], 50);
    PlayerTextDrawUseBox(playerid, INV_INPUT[playerid], 1);
    PlayerTextDrawSetProportional(playerid, INV_INPUT[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, INV_INPUT[playerid], 1);

    INV_INPUT_NUM[playerid] = CreatePlayerTextDraw(playerid, 345.500000, 370.500000, "0");
    PlayerTextDrawFont(playerid, INV_INPUT_NUM[playerid], 1);
    PlayerTextDrawLetterSize(playerid, INV_INPUT_NUM[playerid], 0.154165, 0.699999);
    PlayerTextDrawTextSize(playerid, INV_INPUT_NUM[playerid], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_INPUT_NUM[playerid], 0);
    PlayerTextDrawSetShadow(playerid, INV_INPUT_NUM[playerid], 0);
    PlayerTextDrawAlignment(playerid, INV_INPUT_NUM[playerid], 2);
    PlayerTextDrawColor(playerid, INV_INPUT_NUM[playerid], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_INPUT_NUM[playerid], 255);
    PlayerTextDrawBoxColor(playerid, INV_INPUT_NUM[playerid], 50);
    PlayerTextDrawUseBox(playerid, INV_INPUT_NUM[playerid], 0);
    PlayerTextDrawSetProportional(playerid, INV_INPUT_NUM[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, INV_INPUT_NUM[playerid], 0);

    INV_SELECT[playerid][0] = CreatePlayerTextDraw(playerid, 242.000000, 157.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][0], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][0], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][0], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][0], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][0], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][0], 1077885951); 
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][0], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][0], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][0], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][0], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][0], 1);

    INV_SELECT[playerid][1] = CreatePlayerTextDraw(playerid, 295.000000, 157.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][1], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][1], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][1], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][1], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][1], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][1], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][1], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][1], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][1], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][1], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][1], 1);

    INV_SELECT[playerid][2] = CreatePlayerTextDraw(playerid, 348.000000, 157.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][2], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][2], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][2], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][2], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][2], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][2], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][2], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][2], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][2], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][2], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][2], 1);

    INV_SELECT[playerid][3] = CreatePlayerTextDraw(playerid, 242.000000, 208.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][3], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][3], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][3], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][3], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][3], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][3], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][3], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][3], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][3], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][3], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][3], 1);

    INV_SELECT[playerid][4] = CreatePlayerTextDraw(playerid, 295.000000, 208.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][4], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][4], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][4], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][4], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][4], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][4], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][4], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][4], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][4], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][4], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][4], 1);

    INV_SELECT[playerid][5] = CreatePlayerTextDraw(playerid, 348.000000, 208.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][5], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][5], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][5], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][5], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][5], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][5], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][5], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][5], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][5], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][5], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][5], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][5], 1);

    INV_SELECT[playerid][6] = CreatePlayerTextDraw(playerid, 242.000000, 258.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][6], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][6], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][6], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][6], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][6], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][6], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][6], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][6], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][6], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][6], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][6], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][6], 1);

    INV_SELECT[playerid][7] = CreatePlayerTextDraw(playerid, 295.000000, 258.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][7], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][7], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][7], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][7], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][7], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][7], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][7], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][7], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][7], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][7], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][7], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][7], 1);

    INV_SELECT[playerid][8] = CreatePlayerTextDraw(playerid, 348.000000, 258.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][8], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][8], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][8], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][8], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][8], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][8], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][8], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][8], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][8], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][8], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][8], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][8], 1);

    INV_SELECT[playerid][9] = CreatePlayerTextDraw(playerid, 242.000000, 308.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][9], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][9], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][9], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][9], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][9], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][9], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][9], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][9], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][9], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][9], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][9], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][9], 1);

    INV_SELECT[playerid][10] = CreatePlayerTextDraw(playerid, 295.000000, 308.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][10], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][10], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][10], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][10], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][10], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][10], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][10], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][10], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][10], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][10], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][10], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][10], 1);

    INV_SELECT[playerid][11] = CreatePlayerTextDraw(playerid, 348.000000, 308.000000, "ld_dual:white");
    PlayerTextDrawFont(playerid, INV_SELECT[playerid][11], 4);
    PlayerTextDrawLetterSize(playerid, INV_SELECT[playerid][11], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, INV_SELECT[playerid][11], 41.000000, 39.000000);
    PlayerTextDrawSetOutline(playerid, INV_SELECT[playerid][11], 1);
    PlayerTextDrawSetShadow(playerid, INV_SELECT[playerid][11], 0);
    PlayerTextDrawAlignment(playerid, INV_SELECT[playerid][11], 1);
    PlayerTextDrawColor(playerid, INV_SELECT[playerid][11], 1077885951);
    PlayerTextDrawBackgroundColor(playerid, INV_SELECT[playerid][11], 255);
    PlayerTextDrawBoxColor(playerid, INV_SELECT[playerid][11], 50);
    PlayerTextDrawUseBox(playerid, INV_SELECT[playerid][11], 1);
    PlayerTextDrawSetProportional(playerid, INV_SELECT[playerid][11], 1);
    PlayerTextDrawSetSelectable(playerid, INV_SELECT[playerid][11], 1);

    INV_AMOUNT[playerid][0] = CreatePlayerTextDraw(playerid, 244.000000, 159.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][0], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][0], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][0], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][0], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][0], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][0], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][0], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][0], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][0], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][0], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][0], 0);

    INV_AMOUNT[playerid][1] = CreatePlayerTextDraw(playerid, 297.000000, 159.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][1], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][1], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][1], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][1], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][1], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][1], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][1], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][1], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][1], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][1], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][1], 0);

    INV_AMOUNT[playerid][2] = CreatePlayerTextDraw(playerid, 351.000000, 159.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][2], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][2], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][2], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][2], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][2], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][2], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][2], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][2], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][2], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][2], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][2], 0);

    INV_AMOUNT[playerid][3] = CreatePlayerTextDraw(playerid, 244.000000, 210.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][3], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][3], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][3], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][3], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][3], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][3], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][3], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][3], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][3], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][3], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][3], 0);

    INV_AMOUNT[playerid][4] = CreatePlayerTextDraw(playerid, 297.000000, 210.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][4], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][4], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][4], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][4], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][4], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][4], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][4], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][4], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][4], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][4], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][4], 0);

    INV_AMOUNT[playerid][5] = CreatePlayerTextDraw(playerid, 351.000000, 210.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][5], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][5], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][5], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][5], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][5], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][5], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][5], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][5], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][5], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][5], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][5], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][5], 0);

    INV_AMOUNT[playerid][6] = CreatePlayerTextDraw(playerid, 244.000000, 260.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][6], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][6], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][6], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][6], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][6], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][6], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][6], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][6], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][6], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][6], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][6], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][6], 0);

    INV_AMOUNT[playerid][7] = CreatePlayerTextDraw(playerid, 297.000000, 260.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][7], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][7], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][7], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][7], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][7], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][7], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][7], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][7], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][7], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][7], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][7], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][7], 0);

    INV_AMOUNT[playerid][8] = CreatePlayerTextDraw(playerid, 351.000000, 260.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][8], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][8], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][8], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][8], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][8], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][8], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][8], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][8], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][8], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][8], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][8], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][8], 0);

    INV_AMOUNT[playerid][9] = CreatePlayerTextDraw(playerid, 244.000000, 310.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][9], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][9], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][9], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][9], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][9], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][9], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][9], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][9], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][9], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][9], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][9], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][9], 0);

    INV_AMOUNT[playerid][10] = CreatePlayerTextDraw(playerid, 297.000000, 310.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][10], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][10], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][10], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][10], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][10], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][10], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][10], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][10], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][10], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][10], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][10], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][10], 0);

    INV_AMOUNT[playerid][11] = CreatePlayerTextDraw(playerid, 351.000000, 310.000000, "_");
    PlayerTextDrawFont(playerid, INV_AMOUNT[playerid][11], 1);
    PlayerTextDrawLetterSize(playerid, INV_AMOUNT[playerid][11], 0.141665, 0.649999);
    PlayerTextDrawTextSize(playerid, INV_AMOUNT[playerid][11], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_AMOUNT[playerid][11], 0);
    PlayerTextDrawSetShadow(playerid, INV_AMOUNT[playerid][11], 0);
    PlayerTextDrawAlignment(playerid, INV_AMOUNT[playerid][11], 1);
    PlayerTextDrawColor(playerid, INV_AMOUNT[playerid][11], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_AMOUNT[playerid][11], 255);
    PlayerTextDrawBoxColor(playerid, INV_AMOUNT[playerid][11], 50);
    PlayerTextDrawUseBox(playerid, INV_AMOUNT[playerid][11], 0);
    PlayerTextDrawSetProportional(playerid, INV_AMOUNT[playerid][11], 1);
    PlayerTextDrawSetSelectable(playerid, INV_AMOUNT[playerid][11], 0);

    INV_NAME[playerid][0] = CreatePlayerTextDraw(playerid, 243.000000, 186.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][0], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][0], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][0], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][0], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][0], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][0], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][0], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][0], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][0], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][0], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][0], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][0], 0);

    INV_NAME[playerid][1] = CreatePlayerTextDraw(playerid, 296.000000, 186.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][1], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][1], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][1], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][1], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][1], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][1], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][1], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][1], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][1], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][1], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][1], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][1], 0);

    INV_NAME[playerid][2] = CreatePlayerTextDraw(playerid, 349.000000, 186.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][2], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][2], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][2], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][2], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][2], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][2], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][2], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][2], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][2], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][2], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][2], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][2], 0);

    INV_NAME[playerid][3] = CreatePlayerTextDraw(playerid, 243.000000, 237.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][3], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][3], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][3], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][3], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][3], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][3], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][3], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][3], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][3], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][3], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][3], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][3], 0);

    INV_NAME[playerid][4] = CreatePlayerTextDraw(playerid, 296.000000, 237.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][4], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][4], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][4], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][4], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][4], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][4], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][4], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][4], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][4], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][4], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][4], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][4], 0);

    INV_NAME[playerid][5] = CreatePlayerTextDraw(playerid, 349.000000, 237.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][5], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][5], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][5], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][5], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][5], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][5], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][5], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][5], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][5], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][5], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][5], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][5], 0);

    INV_NAME[playerid][6] = CreatePlayerTextDraw(playerid, 243.000000, 287.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][6], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][6], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][6], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][6], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][6], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][6], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][6], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][6], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][6], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][6], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][6], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][6], 0);

    INV_NAME[playerid][7] = CreatePlayerTextDraw(playerid, 296.000000, 287.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][7], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][7], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][7], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][7], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][7], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][7], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][7], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][7], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][7], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][7], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][7], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][7], 0);

    INV_NAME[playerid][8] = CreatePlayerTextDraw(playerid, 349.000000, 287.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][8], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][8], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][8], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][8], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][8], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][8], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][8], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][8], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][8], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][8], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][8], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][8], 0);

    INV_NAME[playerid][9] = CreatePlayerTextDraw(playerid, 243.000000, 337.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][9], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][9], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][9], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][9], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][9], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][9], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][9], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][9], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][9], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][9], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][9], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][9], 0);

    INV_NAME[playerid][10] = CreatePlayerTextDraw(playerid, 296.000000, 337.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][10], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][10], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][10], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][10], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][10], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][10], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][10], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][10], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][10], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][10], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][10], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][10], 0);

    INV_NAME[playerid][11] = CreatePlayerTextDraw(playerid, 349.000000, 337.000000, "_");
    PlayerTextDrawFont(playerid, INV_NAME[playerid][11], 1);
    PlayerTextDrawLetterSize(playerid, INV_NAME[playerid][11], 0.116665, 0.750000);
    PlayerTextDrawTextSize(playerid, INV_NAME[playerid][11], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, INV_NAME[playerid][11], 0);
    PlayerTextDrawSetShadow(playerid, INV_NAME[playerid][11], 0);
    PlayerTextDrawAlignment(playerid, INV_NAME[playerid][11], 1);
    PlayerTextDrawColor(playerid, INV_NAME[playerid][11], -1);
    PlayerTextDrawBackgroundColor(playerid, INV_NAME[playerid][11], 255);
    PlayerTextDrawBoxColor(playerid, INV_NAME[playerid][11], 50);
    PlayerTextDrawUseBox(playerid, INV_NAME[playerid][11], 0);
    PlayerTextDrawSetProportional(playerid, INV_NAME[playerid][11], 1);
    PlayerTextDrawSetSelectable(playerid, INV_NAME[playerid][11], 0);

	INV_MODEL[playerid][0] = CreatePlayerTextDraw(playerid, 252.500000, 161.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][0], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][0], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][0], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][0], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][0], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][0], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][0], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][0], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][0], 1, 1);

	INV_MODEL[playerid][1] = CreatePlayerTextDraw(playerid, 305.500000, 161.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][1], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][1], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][1], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][1], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][1], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][1], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][1], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][1], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][1], 1, 1);

	INV_MODEL[playerid][2] = CreatePlayerTextDraw(playerid, 359.500000, 161.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][2], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][2], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][2], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][2], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][2], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][2], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][2], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][2], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][2], 1, 1);

	INV_MODEL[playerid][3] = CreatePlayerTextDraw(playerid, 252.500000, 212.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][3], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][3], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][3], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][3], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][3], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][3], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][3], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][3], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][3], 1, 1);

	INV_MODEL[playerid][4] = CreatePlayerTextDraw(playerid, 305.500000, 212.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][4], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][4], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][4], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][4], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][4], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][4], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][4], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][4], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][4], 1, 1);

	INV_MODEL[playerid][5] = CreatePlayerTextDraw(playerid, 359.500000, 212.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][5], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][5], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][5], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][5], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][5], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][5], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][5], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][5], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][5], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][5], 1, 1);

	INV_MODEL[playerid][6] = CreatePlayerTextDraw(playerid, 252.500000, 262.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][6], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][6], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][6], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][6], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][6], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][6], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][6], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][6], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][6], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][6], 1, 1);

	INV_MODEL[playerid][7] = CreatePlayerTextDraw(playerid, 305.500000, 262.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][7], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][7], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][7], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][7], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][7], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][7], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][7], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][7], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][7], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][7], 1, 1);

	INV_MODEL[playerid][8] = CreatePlayerTextDraw(playerid, 359.500000, 262.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][8], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][8], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][8], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][8], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][8], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][8], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][8], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][8], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][8], 1, 1);

	INV_MODEL[playerid][9] = CreatePlayerTextDraw(playerid, 252.500000, 312.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][9], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][9], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][9], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][9], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][9], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][9], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][9], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][9], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][9], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][9], 1, 1);

	INV_MODEL[playerid][10] = CreatePlayerTextDraw(playerid, 305.500000, 312.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][10], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][10], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][10], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][10], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][10], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][10], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][10], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][10], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][10], 1, 1);

	INV_MODEL[playerid][11] = CreatePlayerTextDraw(playerid, 359.500000, 312.000000, "Preview_Model");
	PlayerTextDrawFont(playerid, INV_MODEL[playerid][11], 5);
	PlayerTextDrawLetterSize(playerid, INV_MODEL[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, INV_MODEL[playerid][11], 17.000000, 27.500000);
	PlayerTextDrawSetOutline(playerid, INV_MODEL[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, INV_MODEL[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, INV_MODEL[playerid][11], 1);
	PlayerTextDrawColor(playerid, INV_MODEL[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, INV_MODEL[playerid][11], 0);
	PlayerTextDrawBoxColor(playerid, INV_MODEL[playerid][11], 255);
	PlayerTextDrawUseBox(playerid, INV_MODEL[playerid][11], 0);
	PlayerTextDrawSetProportional(playerid, INV_MODEL[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, INV_MODEL[playerid][11], 0);
	PlayerTextDrawSetPreviewModel(playerid, INV_MODEL[playerid][11], 2663);
	PlayerTextDrawSetPreviewRot(playerid, INV_MODEL[playerid][11], -16.000000, 0.000000, -28.000000, 1.000000);
	PlayerTextDrawSetPreviewVehCol(playerid, INV_MODEL[playerid][11], 1, 1);
}